const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
const APP_VERSION='qixi-video-chat-aware-trailer-20260709-1';
let timer,posterCount=0,posterIndex=-1,stones=20,audioCtx,sfxBus,fxOn=true;
const posters=[
 {scene:'campus',title:'桃子汽水让给你',genre:'校园轻喜剧 · 今天',slogan:'喜欢不是让步，是记得你想要什么。',summary:'便利店冰柜前，两只手同时伸向最后一瓶桃子汽水。谁也不承认自己想让，争论却越来越像约会。',ending:'冰柜补货了。\n这次要不要一人一瓶？'},
 {scene:'noir',title:'今天不许硬撑',genre:'都市治愈片 · 今天',slogan:'先把今天过完，其他的我陪你排队。',summary:'周五下班前，一份过分具体的待办清单出现在聊天框。第一项是喝水，最后一项是一起吃夜宵。',ending:'清单还剩最后一项。\n你要不要现在下楼？'},
 {scene:'snow',title:'猫跑到哪里了',genre:'小冒险片 · 今天',slogan:'普通一天，也可以突然变得很好看。',summary:'他们本来只是出门买晚饭，却因为一只跑丢的小猫绕了半个小区。饭凉了，笑声却没停。',ending:'猫回家了。\n晚饭要不要重新买？'}
];
const stories=[
 {title:'晚风知道答案',genre:'青春爱情片',slogan:'有些靠近，是从一句晚安开始的。',summary:'他们分享天气、晚饭和每一个平常的夜。没有谁说起答案，可那些被认真接住的小事，早已替他们写好了开场。',words:['晚安','今天','下次见','海边','别熬夜','在吗'],quotes:['原来想念，是一件有回声的事。','你接住的，从来不只是一句话。']},
 {title:'星期一逃跑计划',genre:'公路轻喜剧',slogan:'去哪里不重要，同行的人才是方向。',summary:'两个总被日常追赶的人，在无数句“好累”之间，悄悄计划了一场还没出发的旅行。故事从一张车票开始，也可能从一句“走吧”开始。',words:['走吧','奶茶','车站','迟到','哈哈哈','明天'],quotes:['和你浪费的时间，都不算浪费。','下一站叫什么，其实没有关系。']},
 {title:'街角便利店',genre:'都市治愈片',slogan:'有些陪伴，是从同一盏灯下开始的。',summary:'城市快睡着时，街角便利店还亮着。两个总说自己只是路过的人，把没说完的话藏进收银小票里。',words:['睡了吗','热牛奶','猫','下雨','在呢','到家了吗'],quotes:['你不是路过，你只是不好意思说。','那张小票，我其实一直留着。']}
];
let story=stories[0];
const acts=[
 ['开场','每天最后一条消息','深夜 · 两间相隔很远的房间','镜头在两扇亮着的窗之间来回切换。一个人拍下泡得太久的面，另一个人发来窗外的月亮。他们谁也没有重要的事要说，却总能把对话拖到零点以后。每一次“我要睡了”，后面都还跟着三四句话。直到某天，他们不约而同地在输入框里打出“晚安”，又同时笑着撤回。'],
 ['转折','失去回声的十七个小时','雨天 · 公交站与空荡的聊天框','消息停在昨晚的“路上小心”。第二天的早餐、午休和黄昏都没有回复。留下的人反复点亮屏幕，从担心变成生气，又从生气变回担心。雨最大的时候，迟到的电话终于接通。听见那声沙哑的“对不起”，准备好的责怪忽然一句也说不出来。'],
 ['终章','风替他们说完的话','傍晚 · 河堤长椅','他们第一次没有隔着屏幕分享日落。风把没说完的话吹得很轻。一个人问：“以后忙的时候，也可以提前告诉我吗？”另一个人没有立刻回答，只把口袋里的耳机分出一边。电影没有给出告白，只留下两个人并肩走远的背影，和同一首歌的前奏。']
];
const behind=[
 ['NG 花絮','河堤长椅的第七次笑场','终章原本要求两位主演安静对视五秒。第一遍，风把头发吹进嘴里；第二遍，远处遛狗的人突然喊了一声“回家”；第三遍，两个人刚对上视线就一起笑场。摄影机没有停。画面里，一位主演低头捂住脸，另一位把自己的外套递过去挡风。','导演最终保留了笑场前的半秒。那不是表演，是他们真正不知道该拿彼此怎么办的样子。'],
 ['导演讲戏','让“担心”先于“喜欢”被看见','拍摄转折戏时，主演一直把情绪演成争吵。导演叫停，拿起手机演示：先连续点亮屏幕，再放下；走出两步，又折回来。他说，这场戏不是责怪对方为什么没回，而是害怕自己没有资格问。重拍时，主演删掉所有激烈动作，只在电话接通后攥紧伞柄。','这个调整让关系第一次越过普通朋友的边界：角色仍未承认喜欢，却已经无法假装对方的消失与自己无关。'],
 ['删减片段','凌晨一点的便利店','这一场原本位于转折之后。电话挂断，两个人在不同城区走进同一品牌的便利店，同时买下热牛奶。镜头交叉剪辑：一个人在货架前输入“其实我很担心”，另一个人输入“下次不会让你等”。他们都没有发送，最后只拍下牛奶盒，问对方：“你那里也下雨了吗？”','片段长达两分四十秒，完整呈现他们如何把直白的关心重新藏回日常。因节奏被删，但片尾仍保留两张几乎相同的牛奶照片。']
];
const filmDetails={
 campus:{words:['晚自习','操场','便利店','同桌','自行车','奶茶店','社团教室','小猫贴纸','放学见']},
 noir:{words:['便利店','工牌','电梯口','外卖袋','咖啡杯','公司茶水间','医院走廊','小区电梯','24小时洗衣店']},
 space:{words:['便利店','公司茶水间','旧书店','地铁站口','夜宵摊','出租屋阳台','借来的充电线']},
 snow:{words:['长途巴士站','北方小镇','海边民宿','高速服务区','外婆家的厨房','县城照相馆','热咖啡']},
 gothic:{words:['老剧院后台','旧书店二楼','社区活动室','宴会厅','花店','博物馆寄存处','排练胶带']}
};
const genreBank=[['青春喜剧','campus'],['校园爱情','campus'],['都市爱情','noir'],['都市治愈','noir'],['轻喜剧','campus'],['日常陪伴','campus'],['关系片','noir'],['生活流','campus'],['友情亲密','campus'],['家庭治愈','snow'],['小冒险','snow'],['旅行日常','snow'],['职场爱情','noir'],['日常悬疑','noir'],['误会喜剧','campus'],['邻里故事','noir'],['校园成长','campus'],['小镇日常','snow'],['饭桌电影','campus'],['夜谈治愈','noir'],['社恐约会','campus'],['互怼恋爱','campus']];
const eraBank=['1998年','2008年','2016年','现代','80年代','90年代','初夏','雨季','春节前后','毕业季'];
const toneBank=['甜','好笑','温暖','轻松','暧昧','别扭','陪伴','治愈','热闹','安心','慢热','嘴硬','认真搞笑','日常幸福','互相撑腰'];
const locationBank={campus:['海边中学','旧图书馆','傍晚操场','小区楼下','自习室门口','电影院后排','校门口奶茶店','社团教室'],noir:['便利店门口','地铁站口','深夜咖啡馆','社区电影院','公司茶水间','医院走廊','小区电梯口','24小时洗衣店'],space:['便利店门口','公司茶水间','旧书店','地铁站口','夜宵摊旁','出租屋阳台'],snow:['长途巴士站','北方小镇','周末楼道','海边民宿','高速服务区','社区小站','外婆家的厨房','县城照相馆'],gothic:['老剧院后台','旧书店二楼','社区活动室','婚礼宴会厅','街角花店','博物馆寄存处']};
const objectBank={campus:['一杯被拿错的奶茶','共享耳机','写着奇怪备注的便利贴','两份少冰奶茶','一袋薯片','同一支荧光笔','一张表情包截图','没拆的吸管','小猫贴纸'],noir:['收银小票','钥匙扣','皱掉的外卖单','一袋退烧药','工牌挂绳','便利店关东煮杯','半包纸巾','一份待办清单','电梯卡'],space:['便利店小票','工牌挂绳','保温杯','一盒创可贴','借来的充电线','一袋夜宵','没喝完的豆浆'],snow:['一罐热咖啡','坏掉的行李箱轮子','旧纸箱','红色塑料袋','一张购物清单','一盒刚出锅的饺子','便利店暖宝宝'],gothic:['节目单','一束临时买的花','后台通行证','没拆封的喜糖','一张座位贴纸','排练用胶带']};
const relationBank=['总在互相嘴硬的两个人','每天聊到很晚的朋友','因为小误会越聊越近的同学','同住一栋楼却总在电梯遇见的邻居','下班后才敢说真话的同事','一个总迟到、一个总提前到的人','明明熟悉却装作普通朋友的两个人','会把对方吐槽记进备忘录的人','一边嫌弃一边帮忙收尾的搭档','靠表情包维持体面的暧昧对象'];
const deadlineBank=['周五下班前','电影开场前','便利店打烊前','外卖凉掉以前','家人进门以前','第二天早班车以前','奶茶冰块化掉以前','群消息刷屏以前','电梯到一楼以前','闹钟响第二遍以前','夜宵摊收摊前','作业提交前'];
const titleSceneBank={
 campus:['操场边','借来的伞','蓝色校门','课桌下面','汽水靠窗','放学以后','风吹走廊','奶茶封口','校门口见','耳机分你','吸管别抢','便利店门口'],
 noir:['便利店门口','咖啡凉了','电梯口见','窗边座位','钥匙扣','小票先留','外卖袋','工牌背面','楼下灯亮','收银台后','下班以后','热牛奶'],
 snow:['热咖啡','楼道纸箱','旧围巾','厨房白气','巴士站边','行李箱轮','海边民宿','雪落之前','红色塑料袋','回家路上'],
 gothic:['后台花束','剧场门口','旧书店','节目单','花店打烊','座位贴纸','排练胶带','幕布后面']
};
const titleFlavorBank={
 甜味轻喜剧:['别抢吸管','奶茶封口','你又来了','桃子汽水','小票先留','靠窗座位','表情包外'],
 日常陪伴片:['楼下灯亮','热牛奶','窗边座位','晚安以后','回家路上','豆浆还热','灯还亮着'],
 暧昧拉扯片:['只是顺路','门口见吧','别装不熟','慢点拆穿','靠窗那边','伞先借你'],
 沙雕恋爱片:['吸管别抢','少冰争议','奶茶审判','小票作证','别装大人','桃子汽水'],
 双向守护片:['先别硬撑','待办背面','热水放这','楼下等你','电梯口见','外套拉链'],
 小冒险片:['猫在楼下','绕路买饭','便利店门口','巴士站边','风吹地图','回家路上'],
 成长片:['语音发出','别删掉呀','校门口见','走廊有风','慢慢开口','袖口粉笔'],
 朋友以上片:['普通朋友','钥匙扣','你的口味','门口见吧','下班以后','表情包外'],
 职场小甜片:['电梯口见','咖啡少糖','工牌背面','下班以后','打印机旁','茶水间'],
 夜谈治愈片:['灯还亮着','晚安以后','窗边消息','热牛奶','别关台灯','手机亮着']
};
const usedFilmTitles=new Set();
const pick=a=>a[Math.floor(Math.random()*a.length)];
const titleForbidden=/[0-9０-９一二三四五六七八九十百千万半双两几第次封张天夜年月日号]|小时|分钟|秒|公里|厘米|倒计时|编号|No\.?|Vol|Chapter|Episode|520|1314|心动|命中注定|余生|永远|恋人|未完|迟来|错过|告白|重逢|破镜/;
function titleFromObject(o){return String(o).replace(/^[一二两几半]?(杯|份|袋|张|盒|罐|条|只|支|本|把|个)/,'').replace(/被|的|没拆封|没拆|写着|奇怪|备注|借来|借来的|过分|认真|刚出锅|喝完|拿错/g,'').replace(/便利店关东煮杯/,'关东煮').replace(/收银小票/,'小票').replace(/表情包截图/,'表情包').trim()}
function titleMoodReason(t,ctx){let f=ctx.flavor?.name||ctx.flavor||'';if(/喜剧|沙雕|甜/.test(f))return'轻盈、好笑，适合低风险的小误会';if(/陪伴|治愈|守护|夜谈/.test(f))return'温柔、生活化，适合陪伴与照顾感';if(/暧昧|朋友以上/.test(f))return'克制、有拉扯感，适合关系未命名的故事';if(/冒险|成长/.test(f))return'有行动感，适合当下发生的小变化';return'自然、具体，适合生活流关系电影'}
function makeTitleCandidates(ctx){let flavorName=ctx.flavor?.name||ctx.flavor||'',sceneTitles=titleSceneBank[ctx.scene]||titleSceneBank.campus,flavorTitles=titleFlavorBank[flavorName]||[],obj=titleFromObject(ctx.object),loc=String(ctx.location||'').replace(/深夜/g,'街角').replace(/24小时/g,'').replace(/[0-9０-９]/g,''),texture=String(ctx.texture||'').replace(/十秒|一声|一地|两件|半句|五秒|第.+?次/g,'').replace(/[，。,.].*/,'');return[
  obj,
  loc,
  pick(flavorTitles),
  pick(sceneTitles),
  texture.replace(/在|里|上|下|前|后/g,'').slice(0,8),
  `${obj}旁`.slice(0,8),
  `${loc}见`.slice(0,8),
  pick(sceneTitles)
 ].filter(Boolean).map(t=>t.replace(/[《》“”"'：:？！?,，。.\s]/g,'').trim()).filter(Boolean).map(t=>({title:t,reason:titleMoodReason(t,ctx)}))}
function validTitle(t){return t&&t.length>=2&&t.length<=8&&!titleForbidden.test(t)&&!/AI|活动|故事上映|我们的电影|使用说明|之外|第一项/.test(t)&&!usedFilmTitles.has(t)}
function newTitle(ctx={}){let fallback=['便利店门口','桃子汽水','钥匙扣','热牛奶','旧书店','风吹走廊','咖啡凉了','校门口见','吸管别抢','楼下灯亮'],seen=new Set(),candidates=[...makeTitleCandidates(ctx),...fallback.map(title=>({title,reason:'真实、生活化，适合日常关系电影'}))].filter(c=>validTitle(c.title)&&!seen.has(c.title)&&seen.add(c.title));newTitle.lastCandidates=candidates.slice(0,5);let chosen=newTitle.lastCandidates[0]||{title:'便利店门口',reason:'真实、生活化，适合日常关系电影'};usedFilmTitles.add(chosen.title);return chosen.title}
function sceneTexture(scene){return{campus:['粉笔灰落在袖口','广播里断续的晚自习铃','玻璃窗上没擦干的雨痕','走廊尽头晃动的自行车铃','奶茶封口膜被戳破两次'],noir:['便利店冰柜嗡嗡作响','咖啡杯底压着一张小票','电梯门合上前有人按错了楼层','雨水顺着外卖袋往下滴','地铁广播盖住了半句解释'],space:['出租屋阳台晾着两件校服','公司微波炉停在最后十秒','旧书店门铃响了一下','夜宵摊的塑料凳还没擦干'],snow:['挡风玻璃上结出细小冰花','车厢暖气忽明忽暗','旧围巾沾着汽油和薄荷味','楼道里的纸箱堆到门口','厨房汤锅冒着白气'],gothic:['老剧院后台堆着旧海报','花店门口的水桶漏了一地','节目单被雨泡得发软','宴会厅最后一桌还没收拾']}[scene]||['灯光慢慢暗下来']}
function uniqueCore(scene,type,location,object,relation,deadline,tone,flavor){let texture=pick(sceneTexture(scene)),mystery=pick([`为什么${object}会被认真分成两份？`,`那条撤回的消息，是不是只删掉了一个表情？`,`谁先违反了那条奇怪约定？`,`为什么${relation}突然开始装作很忙？`,`${deadline}前，谁会先承认自己有点在意？`]),gesture=pick(['把吸管插好又假装只是顺手','删掉一句话，改发一个很普通的表情','在最吵的时候忽然压低声音','明明先看见了对方，却低头假装找零钱','把小票折好，认真分成两半','把热饮推过去，嘴上说是买错了','把待办清单第一项改成“不许一个人硬撑”','一边吐槽一边把对方的外套拉链拉好']),secret=pick(['一条没发出去的语音','一张被截图保存的表情包','一只写错名字的杯子','一条没来得及发送的夸奖','一张只拍到半个笑脸的照片','一份标题很幼稚的待办清单','一张写着错误备注的小票']);return{texture,mystery,gesture,secret,voice:flavor.name,firstImage:pick([`${location}的灯亮着，${object}被放在最显眼的位置。`,`${texture}，${relation}因为${object}开始了一场过分认真的争论。`,`电影开场不是大事件，而是有人在${deadline}前，把${object}推到对方面前。`,`有人在${location}等了七分钟，等来一句很轻的：“你又来了。”`]),gesture,secret}}
function posterClassFor(type,scene){if(['小冒险','旅行日常','家庭治愈','小镇日常'].includes(type)||scene==='snow')return'road';if(['日常悬疑'].includes(type))return'suspense';if(['都市爱情','都市治愈','职场爱情','关系片','邻里故事','夜谈治愈'].includes(type)||scene==='noir')return'urban';return'youth'}
const storyFlavorBank=[
 {name:'甜味轻喜剧',mood:'好笑又甜',conflict:'一个低风险但很认真的小误会',ending:'让人笑出来',hooks:['谁先承认自己幼稚，谁就输了。','喜欢不是让步，是记得你想要什么。','吵到最后，反而谁都舍不得结束。']},
 {name:'日常陪伴片',mood:'舒服、安稳、像夜灯',conflict:'一个被反复出现的小习惯悄悄改变',ending:'温暖落地',hooks:['有些陪伴，不需要说得很隆重。','普通的一天，因为有人接住，变得没那么难。','灯不用很亮，有人留着就够了。']},
 {name:'暧昧拉扯片',mood:'轻微紧张、嘴硬、心动',conflict:'两个人都在试探边界但不点破',ending:'甜而不告白',hooks:['靠近这件事，他们谁都不肯先承认。','有些顺路，只有当事人才知道绕了多远。','没有告白，也足够让人心跳。']},
 {name:'沙雕恋爱片',mood:'荒唐、好笑、真诚',conflict:'一条离谱规则把聊天变成大型比赛',ending:'笑着破防',hooks:['认真搞笑的人，最容易不小心真心。','他们把暧昧聊成了语文考试。','越不想输，越先露馅。']},
 {name:'双向守护片',mood:'温柔、可靠、不苦情',conflict:'有人嘴上说没事，另一个人悄悄把事拆小',ending:'踏实治愈',hooks:['今天可以不勇敢，也有人陪你把今天过完。','照顾不是说教，是把难题分成小块。','你不用一个人硬撑。']},
 {name:'小冒险片',mood:'轻快、有电影感',conflict:'普通任务突然变成一趟小小绕路',ending:'今天没有白过',hooks:['计划之外的路，反而最像约会。','他们本来只是出门买点东西。','普通一天，也可以突然变得很好看。']},
 {name:'成长片',mood:'明亮、变勇敢一点',conflict:'其中一人尝试做一个以前不敢做的小动作',ending:'小胜利',hooks:['勇敢有时候只是一条发出去的语音。','今天比昨天多说了一点真话。','小小一步，也值得被认真放映。']},
 {name:'朋友以上片',mood:'自然亲密、难定义',conflict:'旁人看出来了，只有他们还在嘴硬',ending:'暖而暧昧',hooks:['普通朋友不会把你的口味记得这么清楚。','他们不定义关系，却早就有了默契。','有些亲密，藏在太自然的照顾里。']},
 {name:'职场小甜片',mood:'都市、克制、轻喜',conflict:'工作日里的小事故暴露了过分熟悉的习惯',ending:'下班后变甜',hooks:['下班不是结束，是他们终于能说真话。','电梯到一楼之前，谁也别装不熟。','成年人也会因为一杯咖啡紧张。']},
 {name:'夜谈治愈片',mood:'安静、柔软、陪伴',conflict:'深夜聊天把一个坏情绪慢慢讲轻',ending:'安心入睡',hooks:['晚安不是结尾，是有人还在听。','夜很长，但不是一个人熬。','一句普通回复，救回了今天。']}
];
function safeMovieText(s){return String(s).replace(/多年后|重逢|错过|告别|离开|分开|旧恋人|来不及|遗憾/g,m=>({多年后:'今天',重逢:'碰面',错过:'绕路',告别:'散场',离开:'走开一会儿',分开:'各忙各的',旧恋人:'熟悉的人',来不及:'差一点',遗憾:'小插曲'}[m]||m))}
function safeTrailerText(s){return String(s).replace(/他们/g,'你和TA').replace(/两个人/g,'你和TA').replace(/你们/g,'你和TA').replace(/一个人/g,'你').replace(/另一个人/g,'TA').replace(/他\/她/g,'TA').replace(/她/g,'你').replace(/对方/g,'TA')}
let importedChatText='',importedChatName='';
function cleanChatLine(s){return String(s||'').replace(/\[[^\]]{1,32}\]|\d{1,2}:\d{2}(:\d{2})?|20\d{2}[\/\-年.]\d{1,2}[\/\-月.]\d{1,2}日?/g,'').replace(/^.{1,12}[:：]\s*/,'').replace(/\s+/g,' ').trim()}
function getChatInput(){return String(importedChatText||$('#chat-paste')?.value||'').trim()}
function hasAny(text,arr){return arr.some(w=>text.includes(w))}
function uniq(arr){let s=new Set;return arr.filter(x=>x&&!s.has(x)&&s.add(x))}
function scoreWords(text,arr){return arr.reduce((n,w)=>n+(text.match(new RegExp(w.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'g'))||[]).length,0)}
function analyzeChat(raw){let text=String(raw||'').slice(-18000),compact=text.replace(/\s+/g,''),lines=text.split(/\n+/).map(cleanChatLine).filter(l=>l.length>=2&&l.length<=36&&!/^https?:|^\[?(图片|表情|语音|文件)\]?$/i.test(l)),bank=[
 ['奶茶',/奶茶|少冰|全糖|珍珠|椰果|吸管|桃子|汽水/,'一杯奶茶','奶茶店门口','奶茶冰块化掉前'],
 ['晚安',/晚安|睡了|困了|别熬夜|早点睡|睡不着|失眠/,'手机屏幕','窗边床头','灯关掉以前'],
 ['吃饭',/吃饭|晚饭|夜宵|外卖|饿|火锅|早餐|午饭/,'外卖袋','街角小店','外卖凉掉以前'],
 ['下雨',/下雨|雨|伞|淋湿|天气/,'一把伞','便利店门口','雨停以前'],
 ['工作',/上班|下班|加班|老板|同事|开会|工位|公司|摸鱼/,'工牌挂绳','公司电梯口','下班打卡前'],
 ['学习',/考试|作业|上课|老师|学校|自习|图书馆|毕业|论文/,'课桌上的草稿纸','自习室门口','晚自习铃响前'],
 ['猫狗',/猫|小猫|狗|狗狗|宠物|喵|汪/,'小猫贴纸','小区楼下','猫钻进花坛前'],
 ['游戏',/游戏|上号|副本|抽卡|排位|开黑|输赢/,'一张表情包截图','聊天框里','这局结束前'],
 ['出门',/地铁|公交|车站|打车|回家|到家|路上|定位/,'钥匙扣','地铁站口','末班车来以前'],
 ['电影',/电影|影院|票|放映|剧|追剧/,'电影票根','电影院后排','电影开场前'],
 ['生病',/医院|感冒|发烧|药|头疼|胃疼|不舒服/,'一袋退烧药','医院走廊','药效上来以前']
 ],hits=bank.filter(b=>b[1].test(text)),kw=uniq(hits.map(h=>h[0]).concat((compact.match(/晚安|哈哈哈?|想你|抱抱|辛苦|在吗|到家|别熬夜|奶茶|下雨|吃饭|睡觉|上班|加班|考试|猫|电影|游戏|语音|表情包|撤回|笨蛋|哼|才没有|顺路|陪你/g)||[]))).slice(0,16);
 let scores={甜味轻喜剧:scoreWords(compact,['哈哈','笑死','可爱','好吃','奶茶','开心','亲亲','抱抱']),暧昧拉扯片:scoreWords(compact,['才没有','你猜','哼','随便','顺路','想你','在吗','撤回','等你','嘴硬']),沙雕恋爱片:scoreWords(compact,['笑死','哈哈哈','离谱','笨蛋','无语','救命','哈哈','别闹']),双向守护片:scoreWords(compact,['辛苦','累','没事','别熬夜','陪你','抱抱','吃药','喝水','不舒服']),日常陪伴片:scoreWords(compact,['晚安','到家','吃饭','今天','睡了','早安','在呢']),夜谈治愈片:scoreWords(compact,['睡不着','失眠','难受','不开心','哭','烦','累','没事']),小冒险片:scoreWords(compact,['出门','路上','打车','地铁','找','迷路','猫','回家']),朋友以上片:scoreWords(compact,['普通朋友','懂你','记得','习惯','口味','下次','一起'])};
 let flavorName=Object.entries(scores).sort((a,b)=>b[1]-a[1])[0]?.[0]||'日常陪伴片';if(!text.trim()||scores[flavorName]===0)flavorName='';
 let scene=hasAny(compact,['上班','下班','公司','医院','地铁','咖啡'])?'noir':hasAny(compact,['车站','出门','路上','旅行','猫','回家'])?'snow':hasAny(compact,['学校','考试','作业','图书馆','上课','奶茶'])?'campus':'campus';
 let type={甜味轻喜剧:'轻喜剧',暧昧拉扯片:'都市爱情',沙雕恋爱片:'误会喜剧',双向守护片:'都市治愈',日常陪伴片:'日常陪伴',夜谈治愈片:'夜谈治愈',小冒险片:'小冒险',朋友以上片:'友情亲密'}[flavorName]||'生活流';
 let hit=hits[0],object=hit?.[2],location=hit?.[3],deadline=hit?.[4],phrase=lines.find(l=>/[？?！!～~]|哈哈|晚安|想你|睡|到家|别|你|TA|我/.test(l))||lines[0]||'',talkRatio=(compact.match(/哈哈|笑|救命|离谱|无语|笨蛋|哼/g)||[]).length;
 let relation=talkRatio>4?'一边互怼一边靠近的你和TA':scores.暧昧拉扯片>2?'明明在意却都不肯先说破的你和TA':scores.双向守护片>2||scores.夜谈治愈片>2?'把照顾藏进日常回复里的你和TA':'每天用小事互相陪着的你和TA';
 return{hasChat:!!text.trim(),keywords:kw,phrase,flavor:flavorName,type,scene,object,location,deadline,relation,texture:phrase?`聊天里反复出现的“${phrase.slice(0,18)}”`:'聊天框亮了一下',secret:kw[0]?`那句关于${kw[0]}的小玩笑`:'一条被认真接住的消息'}}
function chatTeaser(chat,ctx){let p=chat.phrase?`“${chat.phrase.slice(0,22)}”`:ctx.object,forms={
  甜味轻喜剧:`你和TA本来只是聊${chat.keywords[0]||ctx.object}，却认真争到谁先笑场。${p}后来成了整部电影最甜的证据。`,
  暧昧拉扯片:`你和TA都没有把话说满，只把${ctx.object}推来推去。最危险的一秒，是聊天框停在“正在输入”。`,
  沙雕恋爱片:`一场关于${chat.keywords[0]||ctx.object}的离谱争论，把你和TA的聊天变成恋爱判罚现场。谁先破功，谁就输了。`,
  双向守护片:`你说没事，TA没有拆穿，只把${ctx.object}和一句很具体的提醒放到你面前。电影从这里开始变暖。`,
  夜谈治愈片:`那晚你和TA没有聊什么大事，只是一句一句把坏情绪说轻。${p}被留在了片头。`,
  日常陪伴片:`你和TA的聊天没有大事件，只有反复出现的${chat.keywords[0]||'晚安'}、报备和小玩笑。可电影偏偏从这些地方开始。`,
  小冒险片:`你和TA本来只想处理${ctx.object}，结果被一条消息带着绕远。普通一天忽然有了剧情。`,
  朋友以上片:`你和TA都说这只是习惯，可${ctx.object}、口味和回复时间已经替你们说漏了太多。`
};return safeMovieText(forms[ctx.flavor.name]||forms.日常陪伴片).slice(0,92)}
function makeTrailerLines(ctx){let{title,flavor,location,object,deadline,chat,core}=ctx,p=chat.phrase?`“${chat.phrase.slice(0,18)}”`:'“你是不是又嘴硬？”',key=chat.keywords[0]||object,sets={
  甜味轻喜剧:[[`${object}被放在你和TA中间。`,`你们开始翻聊天记录找证据。`,p,`TA先笑了，却说是你赢。`,`《${title}》 喜欢，是记得你的口味。`]],
  暧昧拉扯片:[[`你把消息删掉，又重新输入。`,`${location}的灯亮着，${object}没被拿走。`,p,`TA说只是顺路，你没有拆穿。`,`《${title}》 有些靠近，故意慢半拍。`]],
  沙雕恋爱片:[[`${deadline}，你和TA定下一条怪规则。`,`谁先提到${key}，谁就请客。`,p,`聊天框沉默三秒，然后同时破功。`,`《${title}》 认真搞笑的人，最先露馅。`]],
  双向守护片:[[`你说没事。`,`TA把${object}放到你面前。`,p,`${core.texture}。`,`《${title}》 今天先别一个人硬撑。`]],
  夜谈治愈片:[[`房间只剩手机屏幕亮着。`,`你发来的消息停在${key}。`,p,`TA没有催，只回了很轻的一句。`,`《${title}》 晚安不是自动回复。`]],
  日常陪伴片:[[`你和TA又聊到很晚。`,`${object}旁边，聊天框还亮着。`,p,`没有大事，可谁都没舍得先走。`,`《${title}》 普通一天，也值得放映。`]],
  小冒险片:[[`${deadline}，你和TA临时出门。`,`本来只是为了${object}。`,p,`路线错了，笑声却没停。`,`《${title}》 绕远路也算约会。`]],
  朋友以上片:[[`你说只是普通聊天。`,`TA却记得${key}和你的习惯。`,p,`${object}被自然地推到你这边。`,`《${title}》 不定义，也很亲近。`]]
};return pick(sets[flavor.name]||sets.日常陪伴片).map(s=>safeTrailerText(safeMovieText(s)))}
function buildFilm(){let chat=analyzeChat(getChatInput()),selected=$('.types .selected')?.textContent?.trim()||'自动匹配',mapped={青春爱情:['校园爱情','campus'],都市治愈:['都市治愈','noir'],治愈日常:['日常陪伴','campus'],浪漫悬疑:['日常悬疑','noir'],公路电影:['小冒险','snow']}[selected],[type,scene]=mapped||(chat.hasChat?[chat.type,chat.scene]:pick(genreBank)),flavor=storyFlavorBank.find(f=>f.name===chat.flavor)||pick(storyFlavorBank),era=pick(eraBank),tone=flavor.name,location=chat.location||pick(locationBank[scene]),object=chat.object||pick(objectBank[scene]),relation=chat.relation||pick(relationBank),deadline=chat.deadline||pick(deadlineBank),base=posters.find(p=>p.scene===scene)||posters[0],core=uniqueCore(scene,type,location,object,relation,deadline,tone,flavor);if(chat.hasChat){core.texture=chat.texture||core.texture;core.secret=chat.secret||core.secret;core.firstImage=`${location}里，${object}旁边还留着聊天里那句${chat.phrase?`“${chat.phrase.slice(0,18)}”`:'没有说完的话'}。`}let title=newTitle({scene,type,location,object,flavor,texture:chat.phrase||core.texture}),words=uniq([...(chat.keywords||[]),location,object,deadline,core.secret,core.texture,flavor.name,...filmDetails[scene].words,'今天','刚刚','哈哈哈','别嘴硬','下次一起','我在','早点睡']).slice(0,28);
 let teaserByFlavor={
  甜味轻喜剧:[`${relation}因为${object}吵了二十分钟，最后发现问题不在口味，而在谁先偷偷记住了谁的偏好。`,`${location}今天多了一条奇怪规矩：谁先笑场，谁就负责把${object}让给对方。`],
  日常陪伴片:[`她说自己马上睡，十分钟后又发来一句“你在吗”。于是${location}的灯，被悄悄多留了一会儿。`,`${deadline}前，${relation}照例互相报备小事。真正的剧情，是谁都没发现这已经成了习惯。`],
  暧昧拉扯片:[`他/她总说只是顺手，可${object}每次都刚好出现在她最需要的位置。她没有拆穿，只开始故意慢半拍。`,`${relation}约定今天不许互相试探。结果第一场戏，他们就因为${object}同时破戒。`],
  沙雕恋爱片:[`他们约定谁先说想你谁请客。于是整场聊天变成大型文字躲避赛，连${object}都被拿来当证据。`,`${location}发生了一场过分严肃的审判：${object}到底归谁，双方各执一词，围观群众无人幸免。`],
  双向守护片:[`七夕当天，他/她发来一张待办清单。第一项不是约会，而是：先把今天过完，不许一个人硬撑。`,`${relation}都说自己没事。可${deadline}前，${object}和一份整理好的计划一起出现在聊天框里。`],
  小冒险片:[`他们本来只是去处理${object}，却因为一次走错路，把普通的一天绕成了一场小冒险。`,`${deadline}前，两个人临时接到一个任务：把${object}送到${location}。谁也没想到会这么好玩。`],
  成长片:[`她练了很久才敢把那条语音发出去。对方听完只回了一句：“你刚刚是不是偷笑了？”`,`${relation}今天决定做一件小事：不再把想说的话全都换成表情包。`],
  朋友以上片:[`他们都说只是普通朋友，可${location}的新规矩、${object}的摆放位置，对方比本人还清楚。`,`${relation}的亲密没有名字。它藏在${deadline}前准时出现的提醒，和一句过分自然的“我知道”。`],
  职场小甜片:[`电梯到一楼前，他/她发现对方连自己咖啡少糖都记得。成年人装不熟，原来也会失败。`,`${location}的打印机又卡纸了。两个人一起修了十分钟，却谁也没提真正卡住的是聊天框。`],
  夜谈治愈片:[`${deadline}，她说今天不太好。对方没有讲大道理，只把聊天框一点点整理成能睡着的样子。`,`${location}安静下来以后，只有手机屏幕还亮着。那句“我在”，比任何安慰都来得准时。`]
 },summary=chat.hasChat?chatTeaser(chat,{flavor,object,location}):safeMovieText(pick(teaserByFlavor[flavor.name]||teaserByFlavor.甜味轻喜剧)).slice(0,92);
 let long=safeMovieText(chat.hasChat?`这部电影从你和TA的聊天记录里长出来：${chat.keywords.slice(0,5).join('、')||object}，还有那句${chat.phrase?`“${chat.phrase.slice(0,24)}”`:'被认真接住的话'}。它不把关系写成大起大落，只拍${location}、${object}和几次差点说破又绕回日常的回复。观众会看到的不是模板爱情，而是你和TA之间那种具体、别扭、又很难复制的相处方式。`:`${flavor.name}的节奏里，电影从${location}的一件小事开始：${core.firstImage} ${relation}没有遇到宏大的难题，只是被${core.mystery}这种普通又具体的问题困住。镜头反复拍${object}、${core.texture}和几次差点接上的对话，让观众慢慢看见他们如何把今天过得更靠近一点。`);
 let actPool={
  甜味轻喜剧:[['开场',`奶茶归属案`,`${era} · ${location}`,`${object}被拿错以后，${relation}开始像小学生一样翻聊天记录找证据。一个说“你上次明明说过少冰”，另一个坚持“截图不能断章取义”。`],['转折',`谁先笑谁输`,`中段 · ${deadline}`,`争论升级成临时比赛：谁先笑场谁道歉。结果路过的店员念错名字，两个人同时破功，连刚刚准备好的狠话都没机会说完。`],['终章',`杯套没有扔`,`夜晚 · ${location}`,`事情解决后，${object}的包装被折得整整齐齐。镜头最后拍到杯套背面，那里多了一行很小的字：下次换你选。`]],
  日常陪伴片:[['开场',`第十五分钟回来的人`,`今晚 · ${location}`,`一句“我睡了”发出去后，聊天框安静了十五分钟。然后对方又回来补一句很小的事，像一只嘴硬的猫绕回门口。`],['转折',`灯被提前留好`,`深夜 · ${deadline}`,`另一个人开始提前准备回复：热水、待办、今天的笑话，还有一句不催人的“慢慢说”。生活没有大事件，只是坏情绪被接住了。`],['终章',`晚安不是结束`,`凌晨 · 手机屏幕`,`最后谁也没有正式道谢。屏幕暗下去前，聊天框停在一句很普通的“明天见”，却像把灯留到了天亮。`]],
  暧昧拉扯片:[['开场',`装作顺手`,`今天 · ${location}`,`${relation}都很会装。一个说${core.gesture}只是习惯，另一个点点头，下一秒却故意把路线改得更远。`],['转折',`差点说出口`,`中段 · ${deadline}`,`${object}成了试探的借口。谁都没有问“你是不是在意我”，只是不约而同把话题停在最危险的地方。`],['终章',`没有拆穿`,`傍晚 · ${location}`,`最后一幕没有告白。她只是把${object}往对方那边推了推，说：“下次别这么明显。”对方低头笑了。`]],
  沙雕恋爱片:[['开场',`想你禁止令`,`七夕 · 聊天框`,`${relation}制定了一条离谱规则：谁先说某两个字谁请客。于是普通问候突然变成文字躲避赛。`],['转折',`近义词大战`,`中段 · ${location}`,`他们开始疯狂使用替代表达，从“有点惦记”到“天气需要你点评”。围观的${object}被迫成为裁判。`],['终章',`判罚无效`,`夜晚 · ${deadline}`,`最后两个人同时违规。账单没算清，笑倒是笑了很久。字幕出现前，有人小声说：“那就都请吧。”`]],
  双向守护片:[['开场',`今天先别硬撑`,`早上 · 聊天框`,`${relation}里有一个人说“没事”。另一个人没有追问，只发来一份很短的待办清单，第一项是喝水。`],['转折',`把难题拆小`,`下午 · ${location}`,`${deadline}逼近，焦虑变得很具体。${object}旁边多了三条步骤：先做最容易的，再回消息，最后奖励一份夜宵。`],['终章',`小胜利庆祝`,`晚上 · ${location}`,`事情没有突然变完美，但今天被顺利过完了。最后一个镜头里，${object}旁边贴着新便签：明天也不用一个人。`]],
  小冒险片:[['开场',`出门五分钟`,`今天 · ${location}`,`任务原本很简单：在${deadline}前处理${object}。可路线刚开始就出错，两个人一个负责嘴硬，一个负责导航失败。`],['转折',`临时绕路`,`下午 · 街角`,`${core.secret}让他们不得不多走两条街。普通街景突然变得像电影：便利店、路口、小摊、和一句“反正都出来了”。`],['终章',`饭凉了也没关系`,`夜晚 · ${location}`,`计划没完成得很漂亮，晚饭也凉了。但她第一次觉得，今天不是被耽误了，而是被认真浪费了一次。`]],
  成长片:[['开场',`发送之前`,`今天 · 聊天框`,`${relation}里有一个人盯着语音按钮看了很久。不是因为大事，只是想把一句平常话亲口说出来。`],['转折',`偷笑被听见`,`中段 · ${deadline}`,`语音终于发出去，对面没有评价勇敢，只问：“你刚刚是不是偷笑了？”紧张一下子变成很轻的尴尬。`],['终章',`再发一条`,`晚上 · ${location}`,`最后她又发了一条。比第一条短，也没那么抖。电影把这当成胜利，配乐只响了一小段。`]],
  朋友以上片:[['开场',`普通朋友备忘录`,`今天 · ${location}`,`${relation}都坚持关系普通。但${object}的口味、到达时间、讨厌的称呼，全被另一个人记得太清楚。`],['转折',`旁人看出来了`,`中段 · ${deadline}`,`有人随口问：“你们真的只是朋友？”两个人同时否认，又同时把${object}推给对方。动作比回答诚实。`],['终章',`不定义也可以`,`夜晚 · ${location}`,`最后他们没有给关系起名字。只是一个说“到家说一声”，另一个已经开始打字。`]],
  职场小甜片:[['开场',`打印机事故`,`工作日 · ${location}`,`打印机卡纸，咖啡洒了，${object}也找不到。两个人被迫一起收拾一场小型职场灾难。`],['转折',`装不熟失败`,`电梯口 · ${deadline}`,`同事经过时，他们突然变得客气。可对方一句“你不是不喝冰的吗”，直接让所有装不熟失败。`],['终章',`下班以后`,`夜晚 · 公司楼下`, `下班后，两个人没有马上走。镜头拍他们并排站在便利店灯下，谁也不提加班，只认真讨论明天早餐吃什么。`]],
  夜谈治愈片:[['开场',`今天有点难`,`深夜 · 聊天框`,`${relation}没有见面，只隔着屏幕把一天摊开。一个人说得很乱，另一个人慢慢把每句话接住。`],['转折',`不讲大道理`,`中段 · ${deadline}`,`对方没有说“你要坚强”，只问要不要先洗脸、喝水、把明天最烦的一件事写下来。安慰变得很具体。`],['终章',`能睡着就算赢`,`凌晨 · 房间`, `最后的胜利很小：手机放下，灯关掉，人终于睡着。屏幕上还停着一句“我明天还在”。`]]
 },acts=actPool[flavor.name]||actPool.甜味轻喜剧;
 let quotePool={
  甜味轻喜剧:[`你再装成熟，吸管还是插反了。`,`让给你可以，但你要承认我记性好。`,`这不是吵架，是口味研究。`,`你刚才笑了，判你输。`,`下次别抢，我会主动买两份。`],
  日常陪伴片:[`你说睡了的时候，语气一点都不像。`,`我不催你，我只是把灯留着。`,`今天没发生什么，也可以讲给我听。`,`你回来补那一句，我就知道你还没好。`,`明天见，不是客套。`],
  暧昧拉扯片:[`你每次都说顺手，顺得也太准了。`,`我没有拆穿，是想看你还能装多久。`,`你刚才差一点就问出口了。`,`别退回朋友的位置，那里太挤了。`,`下次明显一点，我可以假装没发现。`],
  沙雕恋爱片:[`“想你”的近义词不算违规吗？`,`你这不是聊天，是逃避判罚。`,`我宣布，天气也不能替你表白。`,`别查词典了，你已经输了。`,`我们两个都犯规，所以都请客。`],
  双向守护片:[`先把今天过完，其他的我陪你排队。`,`你可以说没事，但清单不能骗人。`,`我不是替你解决，我是陪你拆小。`,`今天做到这里，已经很好了。`,`别一个人硬撑，至少把水喝了。`],
  小冒险片:[`我们只是买晚饭，为什么像出任务？`,`导航错了也行，反正你在。`,`饭凉了，但今天没有白过。`,`你负责嘴硬，我负责问路。`,`下次冒险可以提前通知我吗？`],
  成长片:[`你刚刚是不是偷笑了？`,`发出来就已经很厉害了。`,`声音抖也没关系，我听得懂。`,`今天的你，比昨天诚实一点。`,`再发一条吧，我不笑你。`],
  朋友以上片:[`普通朋友会记得这个口味吗？`,`你否认得太快了。`,`我没照顾你，我只是刚好知道。`,`关系可以不命名，习惯已经替我们说了。`,`到家说一声，这句不算越界吧。`],
  职场小甜片:[`你不是不喝冰的吗？`,`装不熟之前，先别叫我常点的咖啡。`,`电梯太快了，我还没想好怎么自然。`,`下班以后，可以不谈工作吗？`,`你把我的习惯记得太职场了。`],
  夜谈治愈片:[`不用总结，乱一点也可以。`,`我在，不是自动回复。`,`先喝水，再骂今天。`,`睡着也没关系，我会把话放轻。`,`明天的你醒来再处理明天。`]
 },quotes=pick([quotePool[flavor.name]||quotePool.甜味轻喜剧]).slice().sort(()=>Math.random()-.5).slice(0,5);
 let behind=[
  ['NG 花絮',`${object}导致的第六次笑场`,`拍摄${location}那场戏时，道具${object}连续几次出现在错误位置。演员本来要认真争论，结果一低头发现它又“自己跑偏”，两个人同时笑到说不出台词。`,`导演最后保留了笑场前的一秒，因为那一下比设计好的心动更自然。`],
  ['导演讲戏',`这场戏要推进的不是悲伤，是默契`,`导演要求演员不要把${flavor.name}演成沉重关系，而是把情绪放进动作里：${core.gesture}。他说观众应该先笑，随后才意识到两个人已经把对方放进日常。`,`这个调整让关系推进更轻：不是谁拯救谁，而是他们一起把一件小事变得值得记住。`],
  ['删减片段',`被剪掉的${deadline}小插曲`,`原片里有一场更长的段落：${relation}为了${object}临时绕去${location}旁边的小店。一路上他们只聊非常无聊的话题，价格、口味、走哪条路，却越聊越像真正的约会。`,`片段因为节奏被删，但其中一句“那下次也这样走吧”被保留进了片尾彩蛋。`]
 ];
 let actorNotes=[`收工以后我在本子上写：这个角色不是不坦率，只是太擅长把关心包装成吐槽。${object}是他/她最好的借口，拿着它就可以自然地靠近一点。`,`我最喜欢${location}那场戏。它没有大起大落，但对方${core.gesture}的时候，我突然觉得角色已经赢了——不是赢过谁，是终于允许自己被陪着。`];
 let endingPool=[
  `片尾字幕走完，聊天框又亮了一下：${flavor.name==='沙雕恋爱片'?'“刚刚那个不算，我要求重赛。”':'“明天如果还这样，我们就按今天的方法来。”'}画面没有继续，只留下输入中的三个点。`,
  `最后的彩蛋是一张照片：${object}被放在桌角，旁边多了一张便签——“下次不用抢，已经给你留了。”`,
  `灯亮前，镜头回到${location}。店员把${object}收进失物招领盒，盒子上贴着一行新字：两个人的东西，请两个人一起来拿。`,
  `片尾最后一秒，手机弹出一条新提醒：明天 ${deadline.replace('前','')}，同一地点。备注只有四个字：别再嘴硬。`
 ],ending=safeMovieText(pick(endingPool));
 let hook=chat.hasChat?(flavor.hooks.find(Boolean)||'普通一天，也值得放映。'):pick(flavor.hooks);
 let trailerLines=makeTrailerLines({title,flavor,location,object,deadline,chat,core});
 let slogan=safeMovieText(hook),posterClass=posterClassFor(type,scene);
 return{...base,title,titleCandidates:newTitle.lastCandidates||[],type,era,tone,storyFlavor:flavor.name,location,object,relation,deadline,posterClass,genre:`${type} · ${flavor.name}`,slogan,summary,logline:summary,long,words,quotes,acts,behind,actorNotes,ending,trailerLines,scene,archiveId:'FILM-'+Date.now().toString(36).toUpperCase()}}
function show(id){$$('.page').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');scrollTo(0,0);sfx('page')}
function render(){let y=$('#you').value.trim()||'你',t=$('#them').value.trim()||'TA';$$('.movie-title').forEach(x=>x.textContent='《'+story.title+'》');$$('.summary').forEach(x=>x.textContent=story.summary);$('.genre').textContent='MOVIE ARCHIVE · LIMITED EDITION';$('.slogan').textContent=story.slogan;$('.names').textContent=`主演 · ${y} × ${t}`;$('.poster-credit').innerHTML=`<span><small>主演</small>${y} × ${t}</span><span><small>上映日期</small>七夕</span><span><small>电影类型</small>${story.genre}</span>`;
 $('.story-logline').textContent=story.logline;
 $('.long-summary').textContent=story.long;
 $('#acts').innerHTML=story.acts.map((a,i)=>`<article data-num="0${i+1}"><i>ACT ${['I','II','III'][i]} · ${a[0]}</i><h3>${a[1]}</h3><p><span class="scene-note">${a[2]}</span>${a[3]}</p></article>`).join('');
 $('#behind').innerHTML=story.behind.map((a,i)=>`<article><span class="index">0${i+1}</span><div><p class="kicker">${a[0]}</p><h2>${a[1]}</h2></div><div class="content"><p>${a[2]}</p><p class="frame">${a[3]}</p></div></article>`).join('');
 $('.final-copy').textContent=`这不是续集预告，而是《${story.title}》留给最后一排观众的隐藏镜头。它不解释结局，只悄悄改变你对前面某一幕的记忆。`;$('.final-message').innerHTML=(story.ending||'片尾最后一秒，某个被忽略的细节重新亮了起来。').replace(/\n/g,'<br>')+'<small>片尾彩蛋</small>';
 $('#quotes').innerHTML=story.quotes.map((q,i)=>`<article class="quote"><span>TAKE 0${i+1}</span><blockquote>“${escHtml(q)}”</blockquote><div><button class="copy" data-i="${i}">复制台词</button>　<button class="cardbtn" data-i="${i}">保存题词卡</button></div></article>`).join('');
 $$('.copy').forEach(b=>b.onclick=()=>{navigator.clipboard?.writeText(story.quotes[+b.dataset.i]||'');b.textContent='已复制 ✓';sfx('click')});$$('.cardbtn').forEach(b=>b.onclick=()=>openQuote(+b.dataset.i));makeGrid()}
function play(){story=buildFilm();posterCount=0;posterIndex=-1;$('.mini-poster').classList.remove('generated');$('.poster-count').textContent='0 / 5';$('.poster-generate small').textContent='首次免费 · 还可生成 5 次';render();show('trailer');let lines=story.trailerLines||['银幕亮起以前','请记住那个被留下的物件','答案不会出现在第一场戏里'],topics=[...story.words,'天气','早餐','晚霞','电影','做梦','生日','旅行','照片','周末','想念','到家了吗','早点休息','下次一起'],line=$('.trailer-line'),wordbox=$('.wordstorm');wordbox.innerHTML='';clearTimeout(timer);let narrate=i=>{if(i>=lines.length){line.classList.remove('visible');timer=setTimeout(()=>flashWord(0),700);return}line.classList.remove('visible');timer=setTimeout(()=>{line.textContent=lines[i];line.classList.add('visible');timer=setTimeout(()=>narrate(i+1),1900+Math.min(lines[i].length*28,700))},420)},flashWord=i=>{if(i>=topics.length){timer=setTimeout(()=>show('hub'),650);return}let w=document.createElement('i');w.textContent=topics[i];w.style.left=8+Math.random()*84+'%';w.style.top=8+Math.random()*84+'%';w.style.fontSize=14+Math.random()*24+'px';wordbox.append(w);timer=setTimeout(()=>flashWord(i+1),150)};narrate(0)}
async function generatePoster(){if(posterCount>=5){$('.poster-generate b').textContent='已生成全部 5 款';sfx('deny');return}if(posterCount>0&&stones<5)return;let img=$('.poster-image'),btn=$('.poster-generate'),small=btn.querySelector('small'),variant=posterCount,style=(hashText(story.title)+variant*3)%8,styleNames=['静物叙事','场景电影','收藏档案','单物极简','生活拼贴','花窗构图','电影俯拍','小型展览'],classNames={youth:'青春爱情',urban:'都市治愈',suspense:'日常悬疑',road:'公路电影'},className=classNames[story.posterClass]||'青春爱情';img.style.opacity='0';btn.classList.add('generating');btn.querySelector('b').textContent=`正在绘制完整画面 · ${styleNames[style]}…`;small.textContent='请稍等，正在连接海报生成服务';try{let response=await fetch('/api/generate-poster',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({film:{title:story.title,genre:story.genre,summary:story.summary,tone:story.tone,location:story.location,object:story.object,posterClass:story.posterClass},variant,style:styleNames[style],className})}),raw=await response.text(),data={};try{data=raw?JSON.parse(raw):{}}catch(e){data={error:raw.slice(0,180)||'接口没有返回 JSON'}}if(!response.ok)throw new Error(`[${response.status}] ${data.error||response.statusText||'Image API request failed'}`);if(!data.image)throw new Error(data.error||'接口成功但没有返回图片');img.src=data.image;await img.decode().catch(()=>{});$('.mini-poster').classList.add('generated');img.style.opacity='1';if(posterCount>0)stones-=5;posterCount++;$('.poster-count').textContent=`${posterCount} / 5 · ${className} · ${styleNames[style]}`;btn.querySelector('b').textContent=posterCount===5?'已生成全部 5 款':`换一种海报 · 5 响石（余 ${stones}）`;small.textContent=posterCount===1?'首次免费 · 还可继续生成不同海报':'每次都会重新绘制不同画面';sfx('magic')}catch(error){img.style.opacity=img.src?'1':'0';let msg=error.message||'未知错误',shortMsg=msg.length>52?msg.slice(0,52)+'…':msg;btn.querySelector('b').textContent=location.protocol==='file:'?'请通过本地服务或部署地址打开':`生成失败：${shortMsg}`;small.textContent=`错误详情：${msg}`;$('.poster-count').textContent=`海报生成失败 · ${msg}`;btn.title=msg;console.error('Poster generation failed:',error);sfx('deny')}finally{btn.classList.remove('generating')}}
function paintPoster(p,seed,v=0){let c=document.createElement('canvas'),x=c.getContext('2d'),W=c.width=900,H=c.height=1350,r=mulberry(seed),pal={campus:['#16191b','#d7cbb6','#7f3030'],noir:['#050708','#18443f','#821f24'],space:['#020409','#153759','#c3a66b'],snow:['#111820','#71808a','#d4c5a6'],gothic:['#080707','#511719','#9b7c49']}[p.scene],flip=v%2?-1:1,ox=[0,-150,130,-90,180][v],oy=[0,100,-120,180,-60][v],g=x.createLinearGradient(v%2?W:0,0,v%2?0:W,H);g.addColorStop(0,pal[v%3===2?1:0]);g.addColorStop(.45+v*.06,pal[1]);g.addColorStop(1,pal[v%2?2:0]);x.fillStyle=g;x.fillRect(0,0,W,H);x.save();x.translate(flip<0?W:0,0);x.scale(flip,1);
 if(p.scene==='campus'){x.strokeStyle='#ddd8';x.lineWidth=6+v*2;for(let i=0;i<10+v;i++){let y=520+oy+i*(68-v*4);x.beginPath();x.moveTo(30+i*10,y);x.lineTo(W-70-i*6,y+v*3);x.stroke()}x.fillStyle=pal[2];let ux=620+ox;x.beginPath();x.moveTo(ux,1010);x.lineTo(ux+150,1250);x.lineTo(ux-35,1215);x.fill();for(let i=0;i<18+v*7;i++){x.save();x.translate(r()*W,180+r()*760);x.rotate(r()*4);x.fillStyle='#eee9';x.fillRect(-22-v*2,-14,44+v*4,28);x.restore()}}
 if(p.scene==='noir'){let bx=255+ox*.65,bw=390-v*24;x.fillStyle=pal[2];x.fillRect(bx,210+oy,bw,650-v*35);x.fillStyle='#080808';x.fillRect(bx+35,260+oy,bw-70,540-v*35);x.strokeStyle=pal[1];x.lineWidth=10+v*5;for(let i=-5;i<8;i++){x.beginPath();x.moveTo(0,250+i*115+oy);x.lineTo(W,20+i*(130-v*3));x.stroke()}x.strokeStyle='#d2373f';x.lineWidth=3+v;x.beginPath();x.moveTo(100,1180-v*60);x.bezierCurveTo(300+ox,650,590-ox,1050,810,430+oy);x.stroke()}
 if(p.scene==='space'){let px=W/2+ox*.65,py=520+oy*.4,pr=300+v*32,rg=x.createRadialGradient(px,py,35,px,py,pr);rg.addColorStop(0,v%2?'#d6b873':'#76a4c9');rg.addColorStop(.55,pal[1]);rg.addColorStop(1,'#020409');x.fillStyle=rg;x.beginPath();x.arc(px,py,pr,0,7);x.fill();x.strokeStyle=pal[2];x.lineWidth=10+v*5;x.beginPath();x.arc(px,py,pr+70+v*10,0,7);x.stroke();for(let i=0;i<55+v*15;i++){x.fillStyle='#fff';x.fillRect(r()*W,r()*H,1+r()*2,1+r()*2)}x.lineWidth=3;x.beginPath();x.moveTo(100,1050-v*30);x.bezierCurveTo(300+ox,850,560-ox,1220,820,950);x.stroke()}
 if(p.scene==='snow'){x.fillStyle='#e4e7e8';for(let i=0;i<220+v*80;i++)x.fillRect(r()*W,r()*H,1+r()*4,1+r()*4);let bx=100+Math.abs(ox)*.5,by=700+oy,bw=700-v*55;x.fillStyle='#101820';x.fillRect(bx,by,bw,230+v*15);x.fillStyle=v%2?'#d6ccb8':'#b39158';for(let i=0;i<3+v%2;i++)x.fillRect(bx+70+i*(bw-150)/4,by+45,90+v*8,76);x.strokeStyle='#eee9';x.lineWidth=5+v;x.beginPath();x.arc(bx+bw*.46,by+92,60+v*6,3.4,6.1);x.arc(bx+bw*.57,by+92,60+v*6,3.3,6);x.stroke()}
 if(p.scene==='gothic'){let cx=W/2+ox*.55,cw=410-v*28;x.fillStyle=pal[1];x.fillRect(cx-cw/2,150+oy,cw,940-v*45);x.strokeStyle=pal[2];x.lineWidth=8+v*4;for(let i=0;i<3+v%3;i++){x.beginPath();x.arc(cx,210+i*(285-v*12),350-i*34,Math.PI,0);x.stroke()}x.fillStyle='#050505aa';x.beginPath();x.ellipse(cx-45,650+oy*.3,70+v*7,220+v*10,-.25,0,7);x.ellipse(cx+65,650+oy*.3,65+v*6,205+v*8,.25,0,7);x.fill()}drawStoryObjects(x,p.scene,v,W,H,pal,r);x.restore();
 let romantic=x.createLinearGradient(0,0,W,H);romantic.addColorStop(0,'#7c5a933d');romantic.addColorStop(.48,'#d7b8db18');romantic.addColorStop(1,'#4d2d6638');x.fillStyle=romantic;x.fillRect(0,0,W,H);let moon=x.createRadialGradient(W*.72,H*.22,8,W*.72,H*.22,260);moon.addColorStop(0,'#fff9dbd9');moon.addColorStop(.22,'#e8d4ff66');moon.addColorStop(1,'#a783bf00');x.fillStyle=moon;x.fillRect(0,0,W,H);x.strokeStyle='#d8bd7ccc';x.lineWidth=4;x.strokeRect(25,25,W-50,H-50);x.lineWidth=1;x.strokeRect(38,38,W-76,H-76);for(let i=0;i<34;i++){x.save();x.translate(r()*W,r()*H);x.rotate(r()*6.28);x.fillStyle=i%4?'#d7b4d99a':'#ead49a9a';x.beginPath();x.ellipse(0,0,4+r()*8,11+r()*15,.4,0,7);x.fill();x.restore()}let vign=x.createRadialGradient(W/2,H/2,300,W/2,H/2,850);vign.addColorStop(.35,'#0000');vign.addColorStop(1,'#160e20b8');x.fillStyle=vign;x.fillRect(0,0,W,H);x.globalAlpha=.11;for(let i=0;i<45000;i++){let q=r()*255;x.fillStyle=`rgb(${q},${q},${q})`;x.fillRect(r()*W,r()*H,1,1)}return c.toDataURL('image/jpeg',.92)}
function mulberry(a){return()=>{a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
function drawStoryObjects(x,scene,v,W,H,pal,r){x.save();x.strokeStyle=pal[2];x.fillStyle=pal[2];x.lineWidth=7;
 if(scene==='campus'&&v===1){for(let i=0;i<7;i++){x.save();x.translate(120+i*105,720+(i%2)*80);x.rotate((i-3)*.08);x.fillStyle='#eee';x.fillRect(-52,-66,104,132);x.fillStyle='#252525';x.fillRect(-39,-52,78,80);x.restore()}}
 if(scene==='campus'&&v===2){x.fillStyle='#ddd9';for(let i=0;i<4;i++)x.fillRect(100+i*195,760,130,250);x.strokeStyle='#fff8';for(let i=0;i<5;i++){x.beginPath();x.moveTo(60,520+i*95);x.lineTo(840,520+i*95);x.stroke()}}
 if(scene==='campus'&&v===3){[285,615].forEach(cx=>{x.beginPath();x.arc(cx,960,115,0,7);x.stroke()});x.beginPath();x.moveTo(285,960);x.lineTo(450,760);x.lineTo(615,960);x.lineTo(410,960);x.closePath();x.stroke()}
 if(scene==='campus'&&v===4){x.fillStyle='#eadfc8';x.fillRect(160,860,250,110);x.fillRect(500,720,250,110);x.strokeStyle='#eee8';for(let i=0;i<5;i++){x.beginPath();x.moveTo(0,1060+i*45);x.lineTo(W,900+i*45);x.stroke()}}
 if(scene==='noir'&&v===1){x.fillStyle='#d5c6aa';for(let i=0;i<5;i++){x.save();x.translate(180+i*120,880-i*35);x.rotate((i-2)*.13);x.fillRect(-65,-90,130,180);x.restore()}x.strokeStyle='#b5232b';x.beginPath();x.moveTo(100,1150);for(let i=0;i<8;i++)x.lineTo(100+r()*700,650+r()*500);x.stroke()}
 if(scene==='noir'&&v===2){x.strokeStyle='#ddd';x.lineWidth=22;x.beginPath();x.arc(440,800,230,.7,2.5);x.stroke();x.lineWidth=7;x.beginPath();x.moveTo(285,960);x.bezierCurveTo(200,1100,650,1000,720,1210);x.stroke()}
 if(scene==='noir'&&v===3){x.strokeStyle='#d9d9d966';for(let i=0;i<8;i++){x.beginPath();x.moveTo(0,500+i*85);x.lineTo(W,500+i*85);x.stroke()}x.fillStyle='#6b1015';x.fillRect(100,980,700,22)}
 if(scene==='noir'&&v===4){x.strokeStyle='#ddd';[300,600].forEach(cx=>{x.beginPath();x.arc(cx,850,140,0,7);x.stroke()});x.beginPath();x.moveTo(440,850);x.lineTo(460,850);x.stroke()}
 if(scene==='space'&&v===1){x.strokeStyle='#d6b873';for(let i=0;i<32;i++){let xx=110+i*22,yy=980+Math.sin(i*.8)*45;x.lineTo(xx,yy)}x.stroke()}
 if(scene==='space'&&v===2){x.strokeStyle='#9bb8cb';x.strokeRect(170,780,560,300);x.beginPath();x.ellipse(450,930,190,90,0,0,7);x.stroke()}
 if(scene==='space'&&v===3){x.fillStyle='#d6b873';for(let i=0;i<4;i++){x.beginPath();x.arc(450,840,35+i*75,0,7);x.globalAlpha=.5-i*.09;x.fill()}x.globalAlpha=1}
 if(scene==='space'&&v===4){x.strokeStyle='#82a5bd';for(let i=0;i<6;i++)x.strokeRect(120+i*115,850+(i%2)*80,90,140);x.fillStyle='#d6b873';x.fillRect(392,790,116,18)}
 if(scene==='snow'&&v===1){x.fillStyle='#eee2cf';for(let i=0;i<8;i++){x.save();x.translate(130+i*95,990+(i%3)*40);x.rotate((i-3)*.12);x.fillRect(-38,-55,76,110);x.restore()}}
 if(scene==='snow'&&v===2){x.fillStyle='#c9c1b2';x.fillRect(340,650,220,135);x.fillStyle='#20252a';x.beginPath();x.moveTo(450,785);x.lineTo(420,980);x.lineTo(480,980);x.fill()}
 if(scene==='snow'&&v===3){x.strokeStyle='#9f3138';x.lineWidth=28;x.beginPath();x.moveTo(80,1050);x.bezierCurveTo(300,700,580,1220,830,800);x.stroke()}
 if(scene==='snow'&&v===4){x.fillStyle='#eadfc8';x.fillRect(170,850,250,115);x.fillRect(490,720,240,110);x.strokeStyle='#77695a';x.setLineDash([8,8]);x.strokeRect(190,870,210,75);x.strokeRect(510,740,200,70);x.setLineDash([])}
 if(scene==='gothic'&&v===1){x.strokeStyle='#c7a261';x.beginPath();x.arc(450,960,110,0,7);x.arc(560,960,110,0,7);x.stroke();for(let i=0;i<30;i++){x.fillStyle='#8a1b22';x.beginPath();x.arc(r()*W,750+r()*450,5+r()*10,0,7);x.fill()}}
 if(scene==='gothic'&&v===2){x.strokeStyle='#d2b879';for(let i=0;i<11;i++){x.beginPath();x.moveTo(450,650);x.lineTo(80+r()*740,300+r()*820);x.stroke()}}
 if(scene==='gothic'&&v===3){x.strokeStyle='#d2b879';x.strokeRect(230,690,440,310);x.beginPath();x.arc(450,845,120,0,7);x.stroke()}
 if(scene==='gothic'&&v===4){x.fillStyle='#15100f';for(let i=0;i<6;i++)x.fillRect(80+i*140,850+(i%2)*50,100,270);x.fillStyle='#721b22';x.beginPath();x.moveTo(610,510);x.lineTo(790,1080);x.lineTo(560,1050);x.fill()}
 x.restore()}
function paintPosterArt(p,seed,style,variant=0){let c=document.createElement('canvas'),x=c.getContext('2d'),W=c.width=900,H=c.height=1350,r=mulberry(seed),sets={youth:[['#f5e8d2','#e6a85c','#7e98a8'],['#fff4dc','#d78471','#678e88'],['#304156','#f1c27d','#ece2ce']],urban:[['#f3f1eb','#a7a8a4','#8f674f'],['#dce2e1','#566168','#c69e74'],['#eee9df','#8c8178','#6d8274']],fantasy:[['#15122d','#63539b','#c1a8e8'],['#081d32','#27839a','#e3cc80'],['#2d1633','#8b466f','#d9b9d8']],suspense:[['#05080d','#153544','#9d1f2b'],['#111217','#42515b','#c19855'],['#061016','#24534d','#ab3030']],road:[['#f1d29a','#bb6943','#617b82'],['#d8d6c2','#708b78','#c58c4d'],['#263b51','#e0ad64','#cbd3d4']],scifi:[['#020711','#174f76','#c9e9f4'],['#08152a','#356fc4','#d7b668'],['#090b18','#794ac6','#6fe2ee']]},cls=p.posterClass||posterClassFor(p.type||'',p.scene),pal=sets[cls][(style+variant)%3],g=x.createLinearGradient(style%2?W:0,0,style%2?0:W,H);g.addColorStop(0,pal[0]);g.addColorStop(.48+variant*.05,pal[1]);g.addColorStop(1,style%3===1?pal[2]:pal[0]);x.fillStyle=g;x.fillRect(0,0,W,H);
 if(style===0){x.fillStyle=pal[0]+'dd';x.beginPath();x.ellipse(W/2,900,390,230,0,0,7);x.fill();x.strokeStyle=pal[2];x.lineWidth=4;x.beginPath();x.moveTo(70,1120);x.lineTo(830,1120);x.stroke();drawMotif(x,p.object,300,830,1.2,pal[2]);drawMotif(x,p.scene==='campus'?'ticket':p.scene==='space'?'star':'letter',590,900,.82,pal[1]);drawMotif(x,p.scene==='gothic'?'rose':'film',465,690,.68,pal[2])}
 if(style===1){drawEnvironment(x,p.scene,W,H,pal,r);drawMotif(x,p.object,style%2?680:210,990,.72,pal[2])}
 if(style===2){x.fillStyle='#e8dfd2';x.fillRect(65,110,770,1130);for(let i=0;i<7;i++){x.save();x.translate(170+r()*560,220+r()*760);x.rotate((r()-.5)*.3);x.fillStyle=i%2?pal[0]:pal[1];x.shadowColor='#0005';x.shadowBlur=18;x.fillRect(-90,-120,180,240);x.strokeStyle=pal[2];x.strokeRect(-76,-105,152,150);x.restore()}x.strokeStyle='#292424';x.lineWidth=12;for(let i=0;i<17;i++){x.strokeRect(110+i*38,1080,24,34)}drawMotif(x,p.object,460,620,1.15,pal[2])}
 if(style===3){x.fillStyle=pal[0];x.fillRect(0,0,W,H);let halo=x.createRadialGradient(W/2,H*.48,20,W/2,H*.48,330);halo.addColorStop(0,pal[1]+'99');halo.addColorStop(1,pal[0]+'00');x.fillStyle=halo;x.fillRect(0,0,W,H);drawMotif(x,p.object,W/2,H*.5,2.15,pal[2])}
 if(style===4){for(let i=0;i<16;i++){x.fillStyle=[pal[0],pal[1],pal[2]][i%3]+'aa';x.beginPath();x.arc(r()*W,r()*H,40+r()*130,0,7);x.fill()}x.strokeStyle=pal[2];x.lineWidth=5;for(let i=0;i<5;i++){x.beginPath();x.moveTo(-50,250+i*210);x.bezierCurveTo(230,80+i*230,600,430+i*120,950,180+i*220);x.stroke()}for(let i=0;i<8;i++)drawMotif(x,i%2?p.object:'film',100+r()*700,190+r()*900,.45+r()*.65,i%3?pal[0]:pal[2])}
 if(style===5){x.fillStyle=pal[0];x.fillRect(0,0,W,H);x.translate(W/2,H*.5);for(let i=0;i<16;i++){x.save();x.rotate(i*Math.PI/8);x.fillStyle=i%2?pal[1]:pal[2];x.globalAlpha=.35;x.beginPath();x.moveTo(0,0);x.lineTo(350,-80);x.lineTo(350,80);x.closePath();x.fill();x.strokeStyle=pal[2];x.stroke();x.restore()}x.globalAlpha=1;x.strokeStyle=pal[2];x.lineWidth=12;x.beginPath();x.arc(0,0,280,0,7);x.stroke();drawMotif(x,p.object,0,0,1.5,pal[2]);x.setTransform(1,0,0,1,0,0)}
 if(style===6){x.fillStyle=pal[0];x.fillRect(0,0,W,H);x.strokeStyle=pal[1];x.lineWidth=3;x.strokeRect(85,110,730,1110);drawMotif(x,p.object,280,420,1.05,pal[2]);drawMotif(x,'ticket',610,330,.9,pal[1]);drawMotif(x,'cup',610,760,1,pal[2]);drawMotif(x,'letter',290,900,.86,pal[1]);x.strokeStyle=pal[2];x.beginPath();x.moveTo(210,610);x.bezierCurveTo(430,500,500,1050,740,930);x.stroke()}
 if(style===7){x.fillStyle=pal[0];x.fillRect(0,0,W,H);x.fillStyle=pal[1]+'55';x.fillRect(90,160,720,900);x.fillStyle=pal[0];x.fillRect(260,850,380,230);x.strokeStyle=pal[2];x.lineWidth=5;x.strokeRect(115,190,670,790);drawMotif(x,p.object,450,620,1.65,pal[2]);x.fillStyle=pal[2];x.fillRect(170,1130,560,3)}drawPosterClassDetails(x,cls,variant,W,H,pal,r,p);
 let vig=x.createRadialGradient(W/2,H/2,280,W/2,H/2,820);vig.addColorStop(.35,'#0000');vig.addColorStop(1,'#0008');x.fillStyle=vig;x.fillRect(0,0,W,H);x.globalAlpha=.1;for(let i=0;i<36000;i++){let q=r()*255;x.fillStyle=`rgb(${q},${q},${q})`;x.fillRect(r()*W,r()*H,1,1)}return c.toDataURL('image/jpeg',.92)}
function drawPosterClassDetails(x,cls,v,W,H,pal,r,p){x.save();x.strokeStyle=pal[2];x.fillStyle=pal[2];x.lineWidth=3;if(cls==='youth'){for(let i=0;i<5+v;i++){x.globalAlpha=.35;x.beginPath();x.ellipse(100+r()*700,250+r()*850,6+r()*10,18+r()*20,r()*3,0,7);x.fill()}x.globalAlpha=1;if(v%2)drawMotif(x,'film',220,1120,.45,pal[2])}if(cls==='urban'){x.globalAlpha=.2;for(let i=0;i<9;i++){x.fillStyle=i%2?pal[1]:pal[2];x.fillRect(40+i*105,450-r()*160,65,700+r()*120)}x.globalAlpha=1;drawMotif(x,v%2?'cup':'letter',720,1050,.45,pal[2])}if(cls==='fantasy'){x.globalAlpha=.55;for(let i=0;i<24;i++){x.fillStyle=i%3?pal[2]:'#fff';x.beginPath();x.arc(r()*W,r()*H,1+r()*4,0,7);x.fill()}x.globalAlpha=1;x.strokeStyle=pal[2];x.beginPath();x.arc(700,260,90,0,7);x.stroke()}if(cls==='suspense'){x.globalAlpha=.25;for(let i=0;i<8;i++){x.strokeStyle=i%2?pal[2]:pal[1];x.beginPath();x.moveTo(r()*W,0);x.lineTo(r()*W,H);x.stroke()}x.globalAlpha=1;drawMotif(x,v%2?'film':'letter',170,1080,.42,pal[2])}if(cls==='road'){x.globalAlpha=.4;x.strokeStyle=pal[2];x.beginPath();x.moveTo(W*.42,H);x.lineTo(W*.48,H*.54);x.moveTo(W*.58,H);x.lineTo(W*.52,H*.54);x.stroke();x.globalAlpha=1;drawMotif(x,v%2?'ticket':'letter',700,1080,.44,pal[2])}if(cls==='scifi'){x.globalAlpha=.35;for(let i=0;i<5;i++){x.strokeStyle=i%2?pal[2]:pal[1];x.strokeRect(70+i*160,200+i%2*90,120,40)}x.beginPath();x.arc(W/2,H*.48,330,0,7);x.stroke();x.globalAlpha=1}x.restore()}
function motifType(o){if(/伞/.test(o))return'umbrella';if(/车票|口供|信|票|小票|照片|节目单|作业本|明信片|收据|便利贴/.test(o))return'paper';if(/耳机|录音/.test(o))return'headphone';if(/电话|来电|手机/.test(o))return'phone';if(/胶卷/.test(o))return'film';if(/手套/.test(o))return'glove';if(/围巾|红线|挂绳/.test(o))return'ribbon';if(/咖啡|奶茶|水|热牛奶|保温杯/.test(o))return'cup';if(/钥匙|打火机/.test(o))return'clock';if(/玫瑰|花/.test(o))return'rose';if(/戒指/.test(o))return'rings';if(/箱|袋|外卖/.test(o))return'box';return o}
function drawMotif(x,o,cx,cy,s,color){let k=motifType(o);x.save();x.translate(cx,cy);x.scale(s,s);x.strokeStyle=color;x.fillStyle=color;x.lineWidth=7;x.lineCap='round';if(k==='umbrella'){x.beginPath();x.arc(0,0,90,Math.PI,0);x.stroke();x.beginPath();x.moveTo(0,0);x.lineTo(0,130);x.quadraticCurveTo(0,170,35,155);x.stroke()}else if(k==='paper'||k==='ticket'||k==='letter'){x.strokeRect(-85,-115,170,230);x.lineWidth=3;for(let i=0;i<5;i++){x.beginPath();x.moveTo(-55,-65+i*32);x.lineTo(50,-65+i*32);x.stroke()}}else if(k==='headphone'){x.beginPath();x.arc(0,0,90,Math.PI,0);x.stroke();x.strokeRect(-105,-8,35,85);x.strokeRect(70,-8,35,85)}else if(k==='phone'){x.beginPath();x.arc(0,0,90,0,7);x.stroke();x.strokeRect(-55,-125,110,250);x.beginPath();x.moveTo(-55,100);x.bezierCurveTo(-160,180,140,190,55,100);x.stroke()}else if(k==='film'){for(let i=-2;i<3;i++){x.strokeRect(i*45-18,-18,36,36)}x.beginPath();x.moveTo(-120,-45);x.lineTo(120,-45);x.moveTo(-120,45);x.lineTo(120,45);x.stroke()}else if(k==='glove'){x.beginPath();x.moveTo(-55,90);x.lineTo(-75,-20);x.lineTo(-52,-115);x.lineTo(-25,-25);x.lineTo(-15,-130);x.lineTo(12,-28);x.lineTo(28,-120);x.lineTo(48,-20);x.lineTo(62,-92);x.lineTo(78,15);x.lineTo(48,90);x.closePath();x.stroke()}else if(k==='pod'){x.beginPath();x.ellipse(0,0,120,60,0,0,7);x.stroke();x.strokeRect(-145,-85,290,170)}else if(k==='ribbon'){x.beginPath();x.moveTo(-130,40);x.bezierCurveTo(-50,-160,55,170,140,-30);x.stroke()}else if(k==='cup'){x.strokeRect(-70,-65,125,130);x.beginPath();x.arc(60,0,45,-1.4,1.4);x.stroke()}else if(k==='clock'){x.beginPath();x.arc(0,0,100,0,7);x.stroke();x.beginPath();x.moveTo(0,0);x.lineTo(5,-62);x.moveTo(0,0);x.lineTo(45,30);x.stroke()}else if(k==='rose'){for(let i=0;i<5;i++){x.save();x.rotate(i*1.25);x.beginPath();x.ellipse(0,-45,38,70,0,0,7);x.stroke();x.restore()}x.beginPath();x.moveTo(0,40);x.lineTo(0,160);x.stroke()}else if(k==='rings'){x.beginPath();x.arc(-42,0,70,0,7);x.arc(42,0,70,0,7);x.stroke()}else{x.strokeRect(-95,-75,190,150)}x.restore()}
function drawEnvironment(x,scene,W,H,pal,r){x.fillStyle=pal[0];x.fillRect(0,H*.63,W,H*.37);x.fillStyle=pal[1];if(scene==='campus'){for(let i=0;i<11;i++)x.fillRect(60+i*12,H*.34+i*68,W-120-i*24,5)}if(scene==='noir'){for(let i=0;i<7;i++)x.fillRect(80+i*115,280+r()*300,70,720-r()*220);x.fillStyle=pal[2];x.fillRect(330,520,240,430)}if(scene==='space'){x.beginPath();x.arc(W*.62,H*.43,280,0,7);x.fill();x.strokeStyle=pal[2];x.lineWidth=15;x.beginPath();x.arc(W*.62,H*.43,360,0,7);x.stroke()}if(scene==='snow'){x.beginPath();x.moveTo(0,780);x.lineTo(230,430);x.lineTo(450,760);x.lineTo(670,350);x.lineTo(W,760);x.closePath();x.fill();x.fillStyle=pal[2];x.fillRect(230,850,440,170)}if(scene==='gothic'){x.fillRect(170,220,560,900);x.strokeStyle=pal[2];x.lineWidth=12;for(let i=0;i<4;i++){x.beginPath();x.arc(W/2,340+i*230,310-i*30,Math.PI,0);x.stroke()}}}
function syncAudioButtons(){
 $$('.fx-toggle').forEach(b=>b.textContent=fxOn?'✧ 音效开':'✧ 音效关')
}
let importedRoles=[];
function escHtml(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function normalizeRoles(input){let raw=Array.isArray(input)?input:(input?.roles||input?.characters||input?.list||[]);return raw.map((r,i)=>typeof r==='string'?{id:'role-'+i,name:r}:{id:r.id||r.roleId||r.characterId||('role-'+i),name:r.name||r.nickname||r.title||r.displayName||r.characterName||r.roleName,desc:r.desc||r.description||r.subtitle||r.tagline||r.personality||'',avatar:r.avatar||r.icon||r.cover||r.image||''}).filter(r=>r.name)}
function readStoredRoles(){let keys=['appCharacters','characters','characterList','roleList','aiRoles','ai_roles','movieRoles','chatRoles'];for(let k of keys){try{let v=localStorage.getItem(k);if(!v)continue;let roles=normalizeRoles(JSON.parse(v));if(roles.length)return roles}catch(e){}}return[]}
function readWindowRoles(){let pools=[window.__APP_CHARACTERS__,window.APP_CHARACTERS,window.appCharacters,window.characters,window.__APP_ROLES__,window.APP_ROLES,window.appRoles];for(let p of pools){let roles=normalizeRoles(p);if(roles.length)return roles}return[]}
function requestNativeRoles(){try{window.parent?.postMessage?.({type:'movie:request-characters'},'*');window.webkit?.messageHandlers?.movieCharacters?.postMessage?.({type:'movie:request-characters'});window.AppBridge?.requestCharacters?.();window.NativeApp?.requestCharacters?.()}catch(e){}}
function setRoleOptions(roles,from='App'){importedRoles=normalizeRoles(roles);renderRoleList(from)}
window.setMovieRoleOptions=setRoleOptions;
window.importMovieRoles=setRoleOptions;
window.addEventListener('message',e=>{let d=e.data||{};if(d.type==='movie:characters'||d.type==='app:characters'||d.characters||d.roles)setRoleOptions(d.characters||d.roles||d,'App')});
function collectRoles(){let roles=[];try{roles=normalizeRoles(window.AppBridge?.getCharacters?.()||window.NativeApp?.getCharacters?.())}catch(e){}if(!roles.length)roles=readWindowRoles();if(!roles.length)roles=readStoredRoles();importedRoles=roles;return roles}
function renderRoleList(from='App'){let box=$('.role-list'),status=$('.role-status');if(!box)return;let roles=importedRoles.length?importedRoles:collectRoles();if(status)status.textContent=$('#them').value.trim()?`已选择 · ${$('#them').value.trim()}`:(roles.length?`检测到 ${roles.length} 个 App 角色`:'未选择角色 · 可手动填写');if(!roles.length){box.innerHTML='<div class="role-empty"><b>还没有读取到 App 角色</b><p>请确认 App 已把角色列表注入页面；你也可以先手动填写 TA 的名字。</p></div>';requestNativeRoles();return}box.innerHTML=roles.map((r,i)=>`<button class="role-option" data-i="${i}"><span>${r.avatar?`<img src="${escHtml(r.avatar)}" alt="">`:escHtml(r.name.slice(0,1))}</span><strong>${escHtml(r.name)}</strong><small>${escHtml(r.desc||'从 App 角色列表导入')}</small></button>`).join('');$$('.role-option').forEach(b=>b.onclick=()=>{let r=roles[+b.dataset.i];$('#them').value=r.name;$('.role-status').textContent=`已选择 · ${r.name}`;$('.role-drawer').classList.remove('open');$('.role-drawer').setAttribute('aria-hidden','true');sfx('click')})}
function applyInitialRoleFromApp(){let p=new URLSearchParams(location.search),name=p.get('roleName')||p.get('characterName')||p.get('role')||p.get('character');if(name){$('#them').value=name.slice(0,12);$('.role-status').textContent=`已导入当前角色 · ${$('#them').value}`}}
function initAudio(){if(audioCtx)return;audioCtx=new(window.AudioContext||window.webkitAudioContext)();sfxBus=audioCtx.createGain();sfxBus.gain.value=fxOn?1:0;sfxBus.connect(audioCtx.destination);syncAudioButtons()}
function setFx(on){fxOn=on;if(audioCtx){sfxBus.gain.value=on?1:0}syncAudioButtons()}
function tone(freq,dur=.36,type='sine',gain=.012,delay=0){let now=audioCtx.currentTime+delay,o=audioCtx.createOscillator(),g=audioCtx.createGain(),f=audioCtx.createBiquadFilter();o.type='sine';o.frequency.value=freq;f.type='lowpass';f.frequency.value=1180;g.gain.setValueAtTime(0,now);g.gain.linearRampToValueAtTime(gain,now+.14);g.gain.setValueAtTime(gain,now+Math.max(.16,dur*.45));g.gain.linearRampToValueAtTime(0,now+dur+.16);o.connect(f).connect(g).connect(sfxBus);o.start(now);o.stop(now+dur+.28)}
function sfx(type){if(!fxOn)return;if(!audioCtx)initAudio();audioCtx.resume?.();if(type==='magic'){[392,493.88].forEach((f,i)=>tone(f,.52,'sine',.009,i*.12));return}if(type==='deny'){tone(246.94,.42,'sine',.008);return}if(type==='page'){tone(329.63,.48,'sine',.007);return}if(type==='soft'){return}tone(440,.34,'sine',.007)}
$$('.fx-toggle').forEach(b=>b.onclick=()=>{setFx(!fxOn);if(fxOn)sfx('click')});
syncAudioButtons();
$$('.types button').forEach(b=>b.onclick=()=>{$$('.types button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');sfx('click')});
$('.role-open').onclick=()=>{renderRoleList();$('.role-drawer').classList.add('open');$('.role-drawer').setAttribute('aria-hidden','false');sfx('page')};
$('.role-close').onclick=()=>{$('.role-drawer').classList.remove('open');$('.role-drawer').setAttribute('aria-hidden','true')};
$('.role-refresh').onclick=()=>{importedRoles=[];renderRoleList();sfx('click')};
$('#them').addEventListener('input',()=>{$('.role-status').textContent=$('#them').value.trim()?`手动填写 · ${$('#them').value.trim()}`:'未选择角色 · 可手动填写'});
$('.import-open').onclick=()=>{$('.import-drawer').classList.add('open');$('.import-drawer').setAttribute('aria-hidden','false');sfx('page')};$('.drawer-close').onclick=()=>$('.import-drawer').classList.remove('open');
function readChatFile(file){return new Promise((resolve,reject)=>{let r=new FileReader();r.onload=()=>resolve(String(r.result||''));r.onerror=()=>reject(r.error||new Error('读取文件失败'));r.readAsText(file,'utf-8')})}
$('#chat-file').onchange=async e=>{let f=e.target.files[0];if(!f)return;$('.import-status').textContent=`正在读取 · ${f.name}`;$('.import-confirm').textContent='正在读取…';try{importedChatText=await readChatFile(f);importedChatName=f.name;$('.import-status').textContent=`已读取 · ${f.name} · ${importedChatText.length} 个字`;$('.import-confirm').textContent='完成导入'}catch(err){importedChatText='';importedChatName='';$('.import-status').textContent='读取失败，请改用粘贴聊天记录';$('.import-confirm').textContent='重新导入';sfx('deny')}};
$('#chat-paste').addEventListener('input',()=>{let p=$('#chat-paste').value.trim();if(p){importedChatText=p;importedChatName='粘贴内容';$('.import-status').textContent=`已读取粘贴内容 · ${p.length} 个字`;$('.import-confirm').textContent='完成导入'}});
$('.import-confirm').onclick=()=>{let f=$('#chat-file').files[0],p=$('#chat-paste').value.trim();if(p){importedChatText=p;importedChatName='粘贴内容'}if(!importedChatText&&!p&&!f){$('.import-confirm').textContent='请先选择或粘贴聊天记录';sfx('deny');return}if(f&&!importedChatText){$('.import-confirm').textContent='文件还在读取，请稍等';sfx('deny');return}$('.import-drawer').classList.remove('open');$('.import-status').textContent=importedChatName?`已导入 · ${importedChatName} · 将按聊天内容生成影片`:`已导入 · ${importedChatText.length} 个字 · 将按聊天内容生成影片`;sfx('magic')};
$('#start').onclick=()=>{initAudio();play()};$('.skip').onclick=()=>{clearTimeout(timer);show('hub')};$('.poster-generate').onclick=generatePoster;
$$('[data-go]').forEach(b=>b.onclick=()=>show(b.dataset.go));$$('.back').forEach(b=>b.onclick=()=>show('hub'));$$('.home').forEach(b=>b.onclick=()=>show('landing'));$('.next').onclick=()=>show('landing');
const labels=['电影主海报','纪念电影票','镜头特写一','台词对白卡一','NG幕后花絮','镜头特写二','主演手札','台词对白卡二','片尾谢幕彩蛋'];
function makeGrid(){let seed=hashText(story.title),v0=paintPosterArt(story,seed,0),v1=paintPosterArt(story,seed+71,1),v2=paintPosterArt(story,seed+193,4),serial='No.'+(20260000+(seed%9999)).toString().padStart(8,'0'),art=(img,label='')=>`<div class="archive-art" style="background-image:url(${img})"><span>${label}</span></div>`,cards=[
 `<div class="archive-card grid-poster"><header><small>01 · MAIN POSTER</small><b>电影主海报</b></header>${art(v0,'')}<footer><h3>《${story.title}》</h3><p>${story.slogan}</p></footer></div>`,
 `<div class="archive-card grid-ticket"><header><small>02 · TICKET</small><b>纪念电影票</b></header><div class="ticket-body"><h3>《${story.title}》</h3><dl><dt>SEAT</dt><dd>L–05 · ROW 20</dd><dt>DATE</dt><dd>QIXI · 20:00</dd><dt>TYPE</dt><dd>${story.genre}</dd></dl><u></u></div><footer><p>${story.slogan}</p></footer></div>`,
 `<div class="archive-card grid-frame"><header><small>03 · FRAME 014</small><b>镜头特写一</b></header>${art(v1,'01:26:35')}<footer><p>${story.quotes[0]}</p></footer></div>`,
 `<div class="archive-card grid-quote"><header><small>04 · QUOTE</small><b>台词对白卡一</b></header><div class="quote-safe"><h3>“${story.quotes[0]}”</h3></div><footer><p>— Movie Archive</p></footer></div>`,
 `<div class="archive-card grid-ng"><header><small>05 · BEHIND THE SCENE</small><b>NG幕后花絮</b></header>${art(v0,'POLAROID')}<footer><h3>${story.behind[0][1]}</h3><p>这里笑场了 ↗</p></footer></div>`,
 `<div class="archive-card grid-wide"><header><small>06 · FRAME 027</small><b>镜头特写二</b></header><div class="wide-clean"><span>WIDE SHOT</span><p>${story.acts[2][2]}</p></div><footer><p>${story.acts[2][1]}</p></footer></div>`,
 `<div class="archive-card grid-notes"><header><small>07 · ACTOR NOTES</small><b>主演手札</b></header><div class="notes-safe"><p><b>TA</b> ${(story.actorNotes&&story.actorNotes[0])||story.quotes[0]}</p><p><b>YOU</b> ${(story.actorNotes&&story.actorNotes[1])||story.quotes[1]}</p></div><footer><p>Signed · ${story.title}</p></footer></div>`,
 `<div class="archive-card grid-dialogue"><header><small>08 · DIALOGUE</small><b>台词对白卡二</b></header>${art(v1,'01:48:02')}<footer><p>${story.quotes[1]}</p></footer></div>`,
 `<div class="archive-card grid-ending"><header><small>09 · AFTER CREDITS</small><b>片尾谢幕彩蛋</b></header><div class="credits-safe"><h3>THE END</h3><p>谢谢观看</p><p>请留到最后一秒</p></div><footer><p>${story.ending.replace(/\n/g,' ')}</p></footer></div>`
 ];$('#grid').innerHTML=cards.map((c,i)=>`<button class="tile tile-${i+1}" data-i="${i}">${c}<span class="archive-mark">MOVIE ARCHIVE · LIMITED EDITION · ${serial}</span></button>`).join('');$$('.tile').forEach(b=>b.onclick=()=>openCard(+b.dataset.i))}
function hashText(s){return [...s].reduce((a,c)=>(a*31+c.charCodeAt(0))>>>0,2166136261)}
let currentSaveName='movie-card',currentSave={kind:'card',index:0},currentPreviewCanvas=null;
function showExportPreview(extraClass=''){currentPreviewCanvas=drawSaveCard();$('#card').className=`card-design export-preview-card ${extraClass}`;$('#card').innerHTML=`<img class="export-preview-img" alt="保存预览" src="${currentPreviewCanvas.toDataURL('image/png')}">`;$('#modal').classList.add('open')}
function openQuote(i){currentSaveName=`${story.title}-台词卡-${i+1}`;currentSave={kind:'quote',index:i,quote:story.quotes[i]||story.quotes[0]||''};showExportPreview('quote-card-modal');sfx('page')}
function openCard(i){currentSaveName=`${story.title}-${labels[i]||'纪念卡'}`;currentSave={kind:'grid',index:i};showExportPreview('card-'+(i+1));sfx('page')}
function textLines(ctx,text,maxWidth){let chars=[...String(text).replace(/\n+/g,' ').replace(/\s+/g,' ').trim()],line='',lines=[];for(let ch of chars){let test=line+ch;if(ctx.measureText(test).width>maxWidth&&line){lines.push(line);line=ch}else line=test}if(line)lines.push(line);return lines}
function fitText(ctx,text,x,y,maxWidth,maxHeight,opt={}){let size=opt.size||44,min=opt.min||22,weight=opt.weight||'500',family=opt.family||'"Noto Serif SC", serif',color=opt.color,align=opt.align||'left',lineRatio=opt.lineRatio||1.55,lines=[];for(;size>=min;size-=2){ctx.font=`${weight} ${size}px ${family}`;lines=textLines(ctx,text,maxWidth);if(lines.length*size*lineRatio<=maxHeight)break}ctx.font=`${weight} ${size}px ${family}`;ctx.textAlign=align;if(color)ctx.fillStyle=color;let lh=size*lineRatio,tx=align==='center'?x+maxWidth/2:x;lines.forEach((l,i)=>ctx.fillText(l,tx,y+i*lh));ctx.textAlign='left';return y+lines.length*lh}
function wrapText(ctx,text,x,y,maxWidth,lineHeight,maxLines){return fitText(ctx,text,x,y,maxWidth,lineHeight*(maxLines||4),{size:Math.max(18,Math.floor(lineHeight*.72)),min:16,lineRatio:lineHeight/Math.max(18,Math.floor(lineHeight*.72))})}
function downloadCanvas(canvas,name){let a=document.createElement('a');a.download=(name||'movie-card').replace(/[\\/:*?"<>|]/g,'-')+'.png';a.href=canvas.toDataURL('image/png');a.style.display='none';document.body.appendChild(a);a.click();requestAnimationFrame(()=>a.remove())}
function drawSaveCard(){let c=document.createElement('canvas'),ctx=c.getContext('2d'),W=1200,H=1200,S=96,seed=hashText(story.title),serial='No.'+(20260000+(seed%9999)),idx=currentSave.index||0,isQuote=currentSave.kind==='quote',quoteText=String(currentSave.quote||story.quotes[idx]||story.quotes[0]||''),dark=!isQuote&&idx===8,ink=dark?'#f6eff7':'#211e1b',muted=dark?'#d8cedd':'#85796a',gold='#a98248',paper=dark?'#17131b':'#f4eee4',soft=dark?'#241b2b':'#e7dccd';c.width=W;c.height=H;ctx.fillStyle=dark?'#100d13':'#eee7dc';ctx.fillRect(0,0,W,H);
 ctx.fillStyle=paper;ctx.fillRect(S,S,W-2*S,H-2*S);ctx.strokeStyle=dark?'#473b4d':'#d7ccbd';ctx.lineWidth=2;ctx.strokeRect(S,S,W-2*S,H-2*S);
 ctx.globalAlpha=.12;for(let i=0;i<2800;i++){let q=dark?220:80;ctx.fillStyle=`rgba(${q},${q},${q},.22)`;ctx.fillRect(S+Math.random()*(W-2*S),S+Math.random()*(H-2*S),1,1)}ctx.globalAlpha=1;
 const meta=isQuote?`QUOTE CARD · TAKE 0${idx+1}`:`0${idx+1} · ${labels[idx]||'MOVIE ARCHIVE'}`;
 function stamp(x=S,y=S+34,light=false){ctx.fillStyle=light?'#f6eff7':gold;ctx.font='500 18px Outfit, Arial';ctx.letterSpacing='';ctx.fillText('MOVIE ARCHIVE · LIMITED EDITION',x,y);ctx.fillStyle=light?'#d8cedd':muted;ctx.font='500 15px Outfit, Arial';ctx.fillText(serial,x,y+26)}
 function rule(y,color=gold){ctx.strokeStyle=color;ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(S,y);ctx.lineTo(W-S,y);ctx.stroke()}
 function rr(x,y,w,h,r,fill,stroke){ctx.beginPath();ctx.moveTo(x+r,y);ctx.lineTo(x+w-r,y);ctx.quadraticCurveTo(x+w,y,x+w,y+r);ctx.lineTo(x+w,y+h-r);ctx.quadraticCurveTo(x+w,y+h,x+w-r,y+h);ctx.lineTo(x+r,y+h);ctx.quadraticCurveTo(x,y+h,x,y+h-r);ctx.lineTo(x,y+r);ctx.quadraticCurveTo(x,y,x+r,y);ctx.closePath();if(fill){ctx.fillStyle=fill;ctx.fill()}if(stroke){ctx.strokeStyle=stroke;ctx.stroke()}}
 function barcode(x,y,w,h,color=ink){ctx.fillStyle=color;for(let i=0;i<50;i++){let bw=2+(i%5)*2;ctx.fillRect(x+i*w/56,y,bw,h)}}
 function sceneBlock(x,y,w,h,variant=0){let g=ctx.createLinearGradient(x,y,x+w,y+h);g.addColorStop(0,dark?'#241a2b':'#f7efe2');g.addColorStop(.55,dark?'#40304a':'#d7c8b5');g.addColorStop(1,dark?'#17131b':'#ece3d7');ctx.fillStyle=g;ctx.fillRect(x,y,w,h);ctx.save();ctx.beginPath();ctx.rect(x,y,w,h);ctx.clip();ctx.globalAlpha=.24;ctx.strokeStyle=gold;for(let i=0;i<6;i++){ctx.beginPath();ctx.moveTo(x-40,y+h*(.18+i*.13));ctx.bezierCurveTo(x+w*.3,y+h*(.05+i*.12),x+w*.65,y+h*(.32+i*.07),x+w+40,y+h*(.14+i*.1));ctx.stroke()}ctx.globalAlpha=.92;drawMotif(ctx,story.object,x+w*(variant%2?.72:.38),y+h*(variant%3?.55:.62),variant%2?.82:1.08,gold);ctx.restore()}
 function quoteA(q){stamp();fitText(ctx,'台词对白卡',S+56,178,W-2*S-112,54,{size:32,min:22,weight:'600',color:ink,lineRatio:1.2});rule(252);fitText(ctx,`“${q}”`,S+74,335,W-2*S-148,470,{size:56,min:22,weight:'500',color:ink,lineRatio:1.7});ctx.fillStyle=gold;ctx.font='500 21px Outfit, Arial';ctx.fillText('QUOTE / MAGAZINE EDITORIAL',S+74,870);fitText(ctx,`《${story.title}》`,S+74,925,W-2*S-148,82,{size:28,min:17,weight:'400',color:muted,lineRatio:1.34})}
 function quoteB(q){sceneBlock(S+28,S+80,W-2*S-56,640,2);ctx.fillStyle='rgba(20,16,18,.66)';ctx.fillRect(S+58,650,W-2*S-116,188);fitText(ctx,`“${q}”`,S+88,690,W-2*S-176,110,{size:31,min:16,weight:'500',color:'#fff',lineRatio:1.46});ctx.fillStyle=ink;ctx.font='500 18px Outfit, Arial';ctx.fillText('01:26:35 · TAKE 02',S+42,S+45);stamp(S+42,1038)}
 function quoteC(q){stamp();ctx.fillStyle='#eadfce';ctx.fillRect(S+72,245,W-2*S-144,585);ctx.strokeStyle='#cfc1ae';ctx.strokeRect(S+72,245,W-2*S-144,585);ctx.fillStyle='rgba(169,130,72,.12)';ctx.fillRect(S+116,218,170,54);ctx.fillRect(W-S-310,815,180,52);ctx.strokeStyle='#c4b29c';ctx.lineWidth=1;for(let i=0;i<7;i++){ctx.beginPath();ctx.moveTo(S+126,350+i*58);ctx.lineTo(W-S-126,350+i*58);ctx.stroke()}fitText(ctx,`“${q}”`,S+150,365,W-2*S-300,320,{size:42,min:17,weight:'500',color:ink,lineRatio:1.68});ctx.fillStyle=gold;ctx.font='500 23px Outfit, Arial';ctx.fillText('ARCHIVE NOTE',S+150,735);fitText(ctx,`写在《${story.title}》之后`,S+150,772,W-2*S-300,52,{size:22,min:15,weight:'400',color:muted,lineRatio:1.25})}
 function quoteD(q){stamp();ctx.fillStyle=soft;ctx.fillRect(S+42,245,W-2*S-84,255);ctx.fillStyle=paper;ctx.fillRect(S+96,548,W-2*S-192,345);ctx.strokeStyle='#cfc1ae';ctx.strokeRect(S+42,245,W-2*S-84,255);ctx.strokeRect(S+96,548,W-2*S-192,345);ctx.fillStyle=gold;ctx.font='500 20px Outfit, Arial';ctx.fillText('SCENE 08 / DIALOGUE STORYBOARD',S+62,218);fitText(ctx,'你和 TA 的这一场戏，停在这句台词上。',S+90,305,W-2*S-180,118,{size:30,min:16,weight:'400',color:muted,lineRatio:1.52});fitText(ctx,`“${q.replace(/[“”]/g,'')}”`,S+145,615,W-2*S-290,205,{size:42,min:17,weight:'600',color:ink,lineRatio:1.55});rule(970)}
 if(isQuote){[quoteA,quoteB,quoteC,quoteD][idx%4](quoteText);return c}
 if(idx===0){sceneBlock(S,S,W-2*S,H-2*S,0);ctx.fillStyle='rgba(244,238,228,.86)';ctx.fillRect(S+52,S+58,W-2*S-104,210);fitText(ctx,`《${story.title}》`,S+82,S+102,W-2*S-164,86,{size:58,min:28,weight:'700',color:ink,lineRatio:1.18});fitText(ctx,story.slogan,S+82,S+195,W-2*S-164,44,{size:24,min:16,weight:'400',color:muted,lineRatio:1.25});stamp(S+70,1015)}
 else if(idx===1){stamp();rr(S+36,330,W-2*S-72,430,28,'#f6efe3','#cdbda9');ctx.fillStyle='#e9ddcd';ctx.fillRect(S+70,330,54,430);for(let y=360;y<735;y+=36){ctx.beginPath();ctx.arc(S+98,y,9,0,7);ctx.fillStyle='#f4eee4';ctx.fill()}fitText(ctx,'MOVIE TICKET',S+160,375,320,42,{size:32,min:22,weight:'600',color:gold,lineRatio:1.1});fitText(ctx,`《${story.title}》`,S+160,450,500,78,{size:42,min:22,weight:'700',color:ink,lineRatio:1.18});[['VIEWER','你 × TA'],['SEAT','L-520'],['TIME','QIXI · 20:00'],['TYPE',story.genre]].forEach((r,i)=>{ctx.fillStyle=muted;ctx.font='500 18px Outfit, Arial';ctx.fillText(r[0],S+160,575+i*44);fitText(ctx,r[1],S+270,555+i*44,360,34,{size:24,min:15,weight:'400',color:ink,lineRatio:1.1})});fitText(ctx,`“${story.slogan}”`,S+675,470,260,120,{size:26,min:16,weight:'400',color:ink,lineRatio:1.45});barcode(S+670,650,300,70);fitText(ctx,serial,S+670,745,300,28,{size:18,min:12,weight:'500',color:muted,lineRatio:1.1})}
 else if(idx===2){sceneBlock(S+34,S+96,W-2*S-68,690,1);ctx.fillStyle='rgba(0,0,0,.48)';ctx.fillRect(S+74,660,W-2*S-148,98);fitText(ctx,story.quotes[0],S+104,690,W-2*S-208,56,{size:28,min:16,weight:'500',color:'#fff',lineRatio:1.3});ctx.fillStyle=gold;ctx.font='500 20px Outfit, Arial';ctx.fillText('01:26:35',S+54,S+64);fitText(ctx,'FRAME 014 · CLOSE-UP SHOT',S+54,850,W-2*S-108,40,{size:22,min:16,weight:'500',color:muted,lineRatio:1.2});stamp(S+54,1006)}
 else if(idx===3){quoteA(story.quotes[0])}
 else if(idx===4){stamp();ctx.fillStyle='#e9dfd2';ctx.fillRect(S+74,210,470,520);ctx.strokeStyle='#fff';ctx.lineWidth=28;ctx.strokeRect(S+102,240,414,330);sceneBlock(S+126,264,366,282,3);ctx.fillStyle='rgba(169,130,72,.18)';ctx.fillRect(S+70,176,170,48);ctx.fillRect(755,706,190,50);ctx.strokeStyle=gold;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(620,290);ctx.lineTo(960,250);ctx.stroke();fitText(ctx,story.behind[0][1],620,320,380,90,{size:34,min:18,weight:'600',color:ink,lineRatio:1.3});fitText(ctx,story.behind[0][2],620,440,380,300,{size:25,min:13,weight:'400',color:muted,lineRatio:1.55});ctx.fillStyle=gold;ctx.font='500 20px Outfit, Arial';ctx.fillText('DIRECTOR NOTE / POLAROID',S+74,830)}
 else if(idx===5){ctx.fillStyle='#eee4d7';ctx.fillRect(S+40,S+72,W-2*S-80,660);ctx.strokeStyle='#cdbfad';ctx.strokeRect(S+40,S+72,W-2*S-80,660);drawMotif(ctx,story.object,W/2,420,1.55,gold);ctx.fillStyle=soft;ctx.fillRect(S+80,785,W-2*S-160,180);fitText(ctx,`${story.acts[2][1]}。${story.acts[2][3]}`,S+112,825,W-2*S-224,92,{size:26,min:13,weight:'400',color:ink,lineRatio:1.45});ctx.fillStyle=gold;ctx.font='500 20px Outfit, Arial';ctx.fillText('FRAME 027 · TOP-DOWN OBJECT SHOT',S+68,S+44);stamp(S+68,1040)}
 else if(idx===6){stamp();ctx.strokeStyle='#cfc1ae';ctx.beginPath();ctx.moveTo(W/2,S+190);ctx.lineTo(W/2,H-S-170);ctx.stroke();fitText(ctx,'你',S+60,220,400,50,{size:38,min:26,weight:'600',color:gold,lineRatio:1.1});fitText(ctx,story.actorNotes?.[1]||story.quotes[1],S+60,300,410,430,{size:31,min:14,weight:'400',color:ink,lineRatio:1.55});fitText(ctx,'TA',W/2+60,220,400,50,{size:38,min:26,weight:'600',color:gold,lineRatio:1.1});fitText(ctx,story.actorNotes?.[0]||story.quotes[0],W/2+60,300,410,430,{size:31,min:14,weight:'400',color:ink,lineRatio:1.55});ctx.fillStyle=muted;ctx.font='400 22px "Noto Serif SC", serif';ctx.fillText('Signed / 你 × TA',S+60,940);rule(995)}
 else if(idx===7){quoteD(story.quotes[1]||story.quotes[0]||'')}
 else if(idx===8){ctx.fillStyle='#141018';ctx.fillRect(S,S,W-2*S,H-2*S);let rg=ctx.createRadialGradient(W/2,430,40,W/2,430,430);rg.addColorStop(0,'#6e557b66');rg.addColorStop(1,'#14101800');ctx.fillStyle=rg;ctx.fillRect(S,S,W-2*S,H-2*S);ctx.textAlign='center';ctx.fillStyle='#f6eff7';ctx.font='700 74px Outfit, Arial';ctx.fillText('THE END',W/2,330);ctx.font='400 28px "Noto Serif SC", serif';ctx.fillText('谢谢观看',W/2,390);drawMotif(ctx,story.object,W/2,575,1.05,'#d7bd82');ctx.textAlign='left';fitText(ctx,story.ending,S+120,760,W-2*S-240,160,{size:30,min:16,weight:'400',color:'#f6eff7',lineRatio:1.55,align:'center'});stamp(S+60,1030,true)}
 return c}
$('.save').onclick=async()=>{let btn=$('.save'),old=btn.textContent;try{btn.textContent='正在保存…';downloadCanvas(currentPreviewCanvas||drawSaveCard(),currentSaveName);btn.textContent='已保存 ✓';setTimeout(()=>btn.textContent=old,1200);sfx('magic')}catch(e){btn.textContent='保存失败';setTimeout(()=>btn.textContent=old,1400);console.error(e);sfx('deny')}};
$$('.x,.x2').forEach(b=>b.onclick=()=>$('#modal').classList.remove('open'));applyInitialRoleFromApp();story=buildFilm();render();
